//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccARqst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccARqst()
        {
            this.AccDDocs = new HashSet<AccDDoc>();
        }
    
        public int AccARqst_Si { get; set; }
        public string AccARqst_Cu { get; set; }
        public System.DateTime AccARqst_DT { get; set; }
        public Nullable<int> AccRqstTyp_Si { get; set; }
        public Nullable<int> AccRqstSts_Si { get; set; }
        public Nullable<double> AccARqst_Prc { get; set; }
        public string AccARqst_Desc { get; set; }
        public string StmpCUs { get; set; }
        public Nullable<System.DateTime> StmpCDT { get; set; }
        public string StmpMUs { get; set; }
        public Nullable<System.DateTime> StmpMDT { get; set; }
        public Nullable<int> AccBudget_Si { get; set; }
        public Nullable<int> AccLK_Si { get; set; }
        public Nullable<int> AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> AccLP_Si { get; set; }
        public Nullable<int> AccLC_Si { get; set; }
    
        public virtual AccBudget AccBudget { get; set; }
        public virtual AccRqstSt AccRqstSt { get; set; }
        public virtual AccRqstTyp AccRqstTyp { get; set; }
        public virtual CtbAccM CtbAccM { get; set; }
        public virtual CtbAccT CtbAccT { get; set; }
        public virtual CtbCost CtbCost { get; set; }
        public virtual CtbProject CtbProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccDDoc> AccDDocs { get; set; }
    }
}
