//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccBudgetPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccBudgetPeriod()
        {
            this.AccBudgetPeriodLogs = new HashSet<AccBudgetPeriodLog>();
        }
    
        public int AccBudgetPeriod_Si { get; set; }
        public int AccBudget_Si { get; set; }
        public int AccBudgetPeriodLevel_Si { get; set; }
        public double AccBudgetPeriod_Price { get; set; }
    
        public virtual AccBudgetPeriodLevel AccBudgetPeriodLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccBudgetPeriodLog> AccBudgetPeriodLogs { get; set; }
    }
}
