//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccBudgetLog
    {
        public int AccBudgetLog_Si { get; set; }
        public int AccBudget_Si { get; set; }
        public double AccBudgetLog_PrcNew { get; set; }
        public double AccBudgetLog_PrcOld { get; set; }
        public double AccBudgetLog_ChangePrc { get; set; }
        public int AccBudgetPeriodLevel_Si { get; set; }
        public bool AccBudgetPeriodLevel_IsNewRow { get; set; }
    
        public virtual AccBudget AccBudget { get; set; }
        public virtual AccBudgetPeriodLevel AccBudgetPeriodLevel { get; set; }
    }
}
