//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccBudget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccBudget()
        {
            this.AccARqsts = new HashSet<AccARqst>();
            this.AccBudgetLogs = new HashSet<AccBudgetLog>();
        }
    
        public int AccBudget_Si { get; set; }
        public string AccBudget_Cu { get; set; }
        public string AccBudget_Tp { get; set; }
        public Nullable<System.DateTime> AccBudget_FromDs { get; set; }
        public Nullable<System.DateTime> AccBudget_ToDs { get; set; }
        public Nullable<int> AccBudgetTyp_Si { get; set; }
        public Nullable<int> AccBudgetH_Si { get; set; }
        public Nullable<int> AccLK_Si { get; set; }
        public Nullable<int> AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> AccLP_Si { get; set; }
        public Nullable<int> AccLC_Si { get; set; }
        public Nullable<double> AccBudget_Prc { get; set; }
        public Nullable<double> AccBudget_PrcCredit { get; set; }
        public Nullable<double> AccBudget_PrcCost { get; set; }
        public Nullable<int> SiFather { get; set; }
        public Nullable<int> AccBudget_TypAcc { get; set; }
        public Nullable<double> AccBudget_PrcRemain { get; set; }
        public Nullable<bool> AccBudget_IsGroup { get; set; }
        public Nullable<int> AccBudget_Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccARqst> AccARqsts { get; set; }
        public virtual AccBudgetH AccBudgetH { get; set; }
        public virtual AccBudgetTyp AccBudgetTyp { get; set; }
        public virtual CtbAccK CtbAccK { get; set; }
        public virtual CtbAccM CtbAccM { get; set; }
        public virtual CtbAccT CtbAccT { get; set; }
        public virtual CtbCost CtbCost { get; set; }
        public virtual CtbProject CtbProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccBudgetLog> AccBudgetLogs { get; set; }
    }
}
