//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCrossCheck
    {
        public int AccCrossCheckId { get; set; }
        public Nullable<int> SiDDoc_Debit { get; set; }
        public Nullable<int> SiDDoc_Credit { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<int> SiAccM { get; set; }
        public Nullable<int> SiAccT { get; set; }
        public Nullable<int> SiCost { get; set; }
        public Nullable<int> SiProject { get; set; }
    }
}
