//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCtbMInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccCtbMInfo()
        {
            this.AccCtbMInfoValues = new HashSet<AccCtbMInfoValue>();
        }
    
        public int AccCtbMInfo_Si { get; set; }
        public Nullable<int> SiAccM { get; set; }
        public string AccCtbMInfo_Tp { get; set; }
        public Nullable<bool> IsInput { get; set; }
        public Nullable<int> AccCtbMInfo_Type { get; set; }
        public Nullable<int> AccCtbMInfoCompany_Si { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> IsUnique { get; set; }
    
        public virtual AccCtbMInfoCompany AccCtbMInfoCompany { get; set; }
        public virtual CtbAccM CtbAccM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccCtbMInfoValue> AccCtbMInfoValues { get; set; }
    }
}
