//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCtbMInfoDefault
    {
        public int AccCtbMInfoDefault_Si { get; set; }
        public Nullable<int> SiAccM { get; set; }
        public string AccCtbMInfo_Tp { get; set; }
        public Nullable<bool> IsInput { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> IsUnique { get; set; }
    
        public virtual CtbAccM CtbAccM { get; set; }
    }
}
