//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCtbMInfoValue
    {
        public int AccCtbMInfoValue_Si { get; set; }
        public Nullable<int> SiDDoc { get; set; }
        public Nullable<int> AccCtbMInfo_Si { get; set; }
        public string AccCtbMInfo_Value { get; set; }
        public Nullable<int> cRow { get; set; }
        public Nullable<int> SiHDoc { get; set; }
    
        public virtual AccCtbMInfo AccCtbMInfo { get; set; }
    }
}
