//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssMachine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssMachine()
        {
            this.AssMachineModels = new HashSet<AssMachineModel>();
            this.AssMachinIds = new HashSet<AssMachinId>();
            this.AssReceptions = new HashSet<AssReception>();
        }
    
        public int AssMachine_Si { get; set; }
        public string AssMachine_Cu { get; set; }
        public string AssMachine_Tp { get; set; }
        public string AssMachine_Serial { get; set; }
        public Nullable<System.DateTime> AssMachine_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssMachineModel> AssMachineModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssMachinId> AssMachinIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssReception> AssReceptions { get; set; }
    }
}
