//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssVchrH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssVchrH()
        {
            this.AssVchrDs = new HashSet<AssVchrD>();
        }
    
        public int AssVchrH_Id { get; set; }
        public Nullable<System.DateTime> AssVchrH_Date { get; set; }
        public Nullable<System.DateTime> AssVchrH_DateFrom { get; set; }
        public Nullable<System.DateTime> AssVchrH_DateUntil { get; set; }
        public string AssVchrH_Tx { get; set; }
        public Nullable<bool> AssVchrH_Sent { get; set; }
        public Nullable<int> AccDocH_Si { get; set; }
        public Nullable<int> AssVchrH_Row { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssVchrD> AssVchrDs { get; set; }
    }
}
