//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssVchrD
    {
        public int AssVchrD_Id { get; set; }
        public int AssVchrH_Id { get; set; }
        public Nullable<int> AssVchrD_ReferenceId { get; set; }
        public string AssVchrD_Tx { get; set; }
        public Nullable<int> AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> AccLC_Si { get; set; }
        public Nullable<int> AccLP_Si { get; set; }
        public decimal AssVchrD_Debit { get; set; }
        public decimal AssVchrD_Credit { get; set; }
        public Nullable<int> AssVchrH_Row { get; set; }
        public Nullable<double> AssVchrD_DebitC { get; set; }
        public Nullable<double> AssVchrD_CreditC { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
    
        public virtual AssVchrH AssVchrH { get; set; }
    }
}
