//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstAssetSelling
    {
        public string AstAsset_Id { get; set; }
        public System.DateTime AstAssetSelling_Date { get; set; }
        public decimal AstAssetSelling_Price { get; set; }
        public string AstAssetSelling_Tx { get; set; }
        public int AccMBank_Si { get; set; }
        public Nullable<int> AccTBank_Si { get; set; }
        public Nullable<int> AccMDepr_Si { get; set; }
        public Nullable<int> AccMAstGrp_Si { get; set; }
        public int AccMBenf_Si { get; set; }
        public Nullable<int> AccTBenf_Si { get; set; }
    
        public virtual AstAsset AstAsset { get; set; }
        public virtual CtbAccM CtbAccM { get; set; }
        public virtual CtbAccM CtbAccM1 { get; set; }
        public virtual CtbAccM CtbAccM2 { get; set; }
        public virtual CtbAccM CtbAccM3 { get; set; }
        public virtual CtbAccT CtbAccT { get; set; }
    }
}
