//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AstAsset()
        {
            this.AstAssetDatas = new HashSet<AstAssetData>();
            this.AstAssetDprcs = new HashSet<AstAssetDprc>();
            this.AstAssetLctns = new HashSet<AstAssetLctn>();
            this.AstAssigns = new HashSet<AstAssign>();
        }
    
        public string AstAsset_Id { get; set; }
        public string AstAsset_Tx { get; set; }
        public string AstGrup_Id { get; set; }
        public Nullable<System.DateTime> AstAsset_ExploitationDate { get; set; }
        public System.DateTime AstAsset_Purchase_Date { get; set; }
        public decimal AstAsset_Purchase_Price { get; set; }
        public Nullable<int> AstAsset_Purchase_VchrId { get; set; }
        public Nullable<System.DateTime> AstAsset_Sale_Date { get; set; }
        public decimal AstAsset_Sale_Price { get; set; }
        public Nullable<int> AstAsset_Sale_VchrId { get; set; }
        public Nullable<System.DateTime> AstAsset_Scrap_Date { get; set; }
        public decimal AstAsset_Scrap_Price { get; set; }
        public Nullable<int> AstAsset_Scrap_VchrId { get; set; }
        public Nullable<System.DateTime> AstAsset_First_Date { get; set; }
        public decimal AstAsset_First_ADepreciate { get; set; }
        public decimal AstAsset_First_BookValue { get; set; }
        public string Astsum_id { get; set; }
        public Nullable<int> PerPrsnl_Si { get; set; }
        public Nullable<int> SiCost { get; set; }
        public Nullable<int> AstLctn_Id { get; set; }
        public Nullable<int> AccM_Si { get; set; }
        public Nullable<int> AccT_Si { get; set; }
        public Nullable<int> Purvndr_Si { get; set; }
        public Nullable<int> AccM_Si_1 { get; set; }
        public Nullable<int> AccT_Si_1 { get; set; }
        public Nullable<int> AccM_Si_2 { get; set; }
        public Nullable<int> AccT_Si_2 { get; set; }
        public Nullable<bool> AstAsset_AccDoc { get; set; }
        public Nullable<bool> AstAsset_AccDoc_1 { get; set; }
        public string Reference { get; set; }
        public string AstAsset_Pelak { get; set; }
        public Nullable<int> AstAsset_DepreciateRate { get; set; }
        public Nullable<System.DateTime> AstAssetDprc_Date { get; set; }
        public Nullable<byte> AssetAssignStatus { get; set; }
        public Nullable<System.DateTime> AssetAssignedDate { get; set; }
        public Nullable<int> SiProject { get; set; }
        public Nullable<bool> AstAsset_AccDoc_2 { get; set; }
        public Nullable<byte> AstAssetDisableCalc { get; set; }
        public Nullable<int> PurVndr_Si1 { get; set; }
        public Nullable<bool> AstAsset_Lock { get; set; }
        public Nullable<bool> AstAsset_IsGift { get; set; }
        public Nullable<bool> AstAsset_Active { get; set; }
        public Nullable<bool> AstAsset_Lockpart { get; set; }
        public string InvGds_Cu { get; set; }
        public Nullable<int> InvDocD_Si { get; set; }
        public Nullable<int> AstInfo1_Si { get; set; }
        public Nullable<int> AstInfo2_Si { get; set; }
        public Nullable<int> AstInfo3_Si { get; set; }
        public Nullable<int> AstInfo4_Si { get; set; }
        public string AstAsset_TxInfo { get; set; }
        public Nullable<int> AstInfo1 { get; set; }
        public Nullable<int> AstInfo2 { get; set; }
        public Nullable<int> AstInfo3 { get; set; }
        public Nullable<int> AstInfo4 { get; set; }
        public Nullable<double> AstAsset_FirstPrc { get; set; }
        public Nullable<double> AstAsset_FirstEst { get; set; }
        public Nullable<double> AstAsset_FirstBookv { get; set; }
        public Nullable<int> AstAsset_CountDay { get; set; }
    
        public virtual AstGrup AstGrup { get; set; }
        public virtual AstLctn AstLctn { get; set; }
        public virtual AstSum AstSum { get; set; }
        public virtual PerPrsnl PerPrsnl { get; set; }
        //public virtual PurVndr PurVndr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AstAssetData> AstAssetDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AstAssetDprc> AstAssetDprcs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AstAssetLctn> AstAssetLctns { get; set; }
        public virtual AstAssetSelling AstAssetSelling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AstAssign> AstAssigns { get; set; }
    }
}
