//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstAssetLctn
    {
        public string AstAsset_Id { get; set; }
        public System.DateTime AstAssetLctn_Date { get; set; }
        public Nullable<int> AstLctn_Id { get; set; }
        public string AstAssetLctn_Tx { get; set; }
        public Nullable<int> SiCost { get; set; }
        public Nullable<int> PerPrsnl_Si { get; set; }
        public Nullable<int> PerPrsnlfrom_Si { get; set; }
    
        public virtual AstAsset AstAsset { get; set; }
        public virtual AstLctn AstLctn { get; set; }
        public virtual CtbCost CtbCost { get; set; }
    }
}
