//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstAssetAjst
    {
        public string AstAsset_Id { get; set; }
        public System.DateTime AstAssetAjst_Date { get; set; }
        public decimal AstAssetAjst_Price { get; set; }
        public string AstAssetAjst_Tx { get; set; }
        public Nullable<short> AstAssetAjst_Type { get; set; }
        public Nullable<int> AstAssetAjst_Si { get; set; }
        public string AstAssetAjst_DocNo { get; set; }
    }
}
