//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstPrm
    {
        public string AstPrms_Lgn { get; set; }
        public Nullable<bool> Assets_IU { get; set; }
        public Nullable<bool> Assets_D { get; set; }
        public Nullable<bool> AssetData_U { get; set; }
        public Nullable<bool> AssetLocation_IUD { get; set; }
        public Nullable<bool> AssetAjust_I { get; set; }
        public Nullable<bool> AssetAjust_U { get; set; }
        public Nullable<bool> AssetAjust_D { get; set; }
        public Nullable<bool> Data_IU { get; set; }
        public Nullable<bool> Data_D { get; set; }
        public Nullable<bool> Calculate { get; set; }
        public Nullable<bool> Locations_IUD { get; set; }
        public Nullable<bool> Groups_IUD { get; set; }
    }
}
