//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstVchrH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AstVchrH()
        {
            this.AstVchrDs = new HashSet<AstVchrD>();
        }
    
        public int AstVchrH_Id { get; set; }
        public Nullable<System.DateTime> AstVchrH_Date { get; set; }
        public Nullable<bool> AstVchrH_Sent { get; set; }
        public Nullable<int> AccDocH_Si { get; set; }
        public string AstVchrH_Tx { get; set; }
        public Nullable<byte> AstVchrH_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AstVchrD> AstVchrDs { get; set; }
    }
}
