//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance
    {
        public Nullable<int> CtbCustVndrTyp_Si { get; set; }
        public Nullable<System.DateTime> ExpirationDate_Dm { get; set; }
        public string ExpirationDate_Ds { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isManualPrice { get; set; }
        public Nullable<int> Limitations_Day { get; set; }
        public Nullable<int> Limitations_Some { get; set; }
        public Nullable<double> percent { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<double> profit { get; set; }
        public Nullable<System.DateTime> Update_Dm { get; set; }
        public string Update_Ds { get; set; }
        public double InvGdsToInv_QtyMax { get; set; }
        public double InvGdsToInv_QtyMin { get; set; }
        public double InvGdsToInv_QtyReal { get; set; }
        public double InvGdsToInv_QtySafe { get; set; }
        public Nullable<double> InvGdsToInv_QtySale { get; set; }
        public double InvGdsToInv_QtyVirtual { get; set; }
        public string InvGdsToInv_Shelf { get; set; }
        public int InvGdsToInv_Si { get; set; }
        public Nullable<int> InvGdsToInv_Tag { get; set; }
        public string InvInvt_Cu { get; set; }
        public string InvInvt_Tp { get; set; }
        public double InvGds_QtyMin { get; set; }
        public string CarCompany { get; set; }
        public int CarId { get; set; }
        public string CarTip { get; set; }
        public string CarType { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> importance { get; set; }
        public Nullable<bool> InvGds_ActiveSale { get; set; }
        public string InvGds_TechNo { get; set; }
        public string InvGds_Cu { get; set; }
        public double InvGds_QtyReal { get; set; }
        public Nullable<double> InvGds_QtySale { get; set; }
        public int InvGds_Si { get; set; }
        public string InvGds_Tp { get; set; }
        public string InvGdsICntry_Tp { get; set; }
        public string InvGdsICratr_Tp { get; set; }
        public int InvUnt_Si { get; set; }
        public string InvUnt_Tp { get; set; }
        public Nullable<double> orderName { get; set; }
        public Nullable<double> Ordr_Cat { get; set; }
        public Nullable<int> parentBundleTypeInvgdsId { get; set; }
        public Nullable<int> parentId { get; set; }
        public int TypeInvgdssId { get; set; }
        public string TypeInvgdssName { get; set; }
        public string Format { get; set; }
        public Nullable<int> Height { get; set; }
        public string Model { get; set; }
        public string Name { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Width { get; set; }
        public string Address { get; set; }
        public bool IsShowPublic { get; set; }
        public Nullable<int> order { get; set; }
        public int CountSale { get; set; }
        public Nullable<decimal> CountSaleBrand { get; set; }
        public Nullable<double> ordrManual { get; set; }
        public Nullable<double> BundlingDetailQty { get; set; }
        public Nullable<int> BundlingHeaderId { get; set; }
        public string Desc { get; set; }
        public string CategoryImagePath { get; set; }
        public string CarImagePath { get; set; }
        public string CarEnglishName { get; set; }
        public string JoinImagePath { get; set; }
        public string CodePro { get; set; }
    }
}
