//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BgtAccIntro
    {
        public int BgtAccIntro_Si { get; set; }
        public int AccM_Si { get; set; }
        public Nullable<byte> BgtAccIntro_Nature { get; set; }
        public Nullable<double> BgtAccIntro_Const { get; set; }
    
        public virtual CtbAccM CtbAccM { get; set; }
    }
}
