//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BgtAssignAccK
    {
        public int BgtAssignAccK_Si { get; set; }
        public Nullable<int> SiAccK { get; set; }
        public Nullable<decimal> BgtAssignAccK_Amnt { get; set; }
        public Nullable<System.DateTime> BgtAssignAccK_Date { get; set; }
    }
}
