//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BgtAssignToCCostSubDetail
    {
        public int BgtAssignToCCostSubDetail_Si { get; set; }
        public Nullable<int> BgtAssignToCCostDetail_Si { get; set; }
        public Nullable<decimal> BgtAssignToCCostSubDetail_Amnt { get; set; }
        public Nullable<System.DateTime> BgtAssignToCCostSubDetail_Date { get; set; }
        public string BgtAssignToCCostSubDetail_Desc { get; set; }
        public Nullable<int> RequestId { get; set; }
    }
}
