//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BgtChangeCostD
    {
        public int BgtChangeCostD_Si { get; set; }
        public int BgtChangeCostH_Si { get; set; }
        public int SiAccM { get; set; }
        public byte BgtChangeCostD_AdjCoef { get; set; }
        public decimal BgtChangeCostD_Cost { get; set; }
    
        public virtual BgtChangeCostH BgtChangeCostH { get; set; }
        public virtual CtbAccM CtbAccM { get; set; }
    }
}
