//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BgtChangeCostH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BgtChangeCostH()
        {
            this.BgtChangeCostDs = new HashSet<BgtChangeCostD>();
        }
    
        public int BgtChangeCostH_Si { get; set; }
        public Nullable<int> CtbCost_Si { get; set; }
        public Nullable<byte> BgtChangeCostH_MonthCoef { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BgtChangeCostD> BgtChangeCostDs { get; set; }
        public virtual CtbCost CtbCost { get; set; }
    }
}
