//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BgtStndrRate
    {
        public int BgtStndrRate_Si { get; set; }
        public int InvGds_Si { get; set; }
        public int InvUnt_Si { get; set; }
        public byte BgtStndrRate_Coef { get; set; }
        public decimal BgtStndrRate_Price { get; set; }
    }
}
