//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CntContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CntContract()
        {
            this.CntAlerts = new HashSet<CntAlert>();
            this.CntAttachments = new HashSet<CntAttachment>();
            this.CntGds = new HashSet<CntGd>();
            this.CntPayments = new HashSet<CntPayment>();
            this.CntReferences = new HashSet<CntReference>();
            this.CntSrvs = new HashSet<CntSrv>();
            this.CntTasks = new HashSet<CntTask>();
            this.CntTracks = new HashSet<CntTrack>();
        }
    
        public int CntContract_Si { get; set; }
        public string CntContract_Number { get; set; }
        public string CntContract_Subject { get; set; }
        public string CntContract_Text { get; set; }
        public string CntContract_Date { get; set; }
        public string CntContract_StartDate { get; set; }
        public string CntContract_EndDate { get; set; }
        public Nullable<decimal> CntContract_Price { get; set; }
        public string CntContract_Description { get; set; }
        public Nullable<int> CntStatus_Si { get; set; }
        public Nullable<int> CntTyp_Si { get; set; }
        public Nullable<int> CntGrp_Si { get; set; }
        public string CntContract_Contractors { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public string CntContract_ContractorNo { get; set; }
        public string CntContract_ContractorDate { get; set; }
        public byte[] CntContract_File { get; set; }
        public string CntContract_FileName { get; set; }
        public string CntContract_ProphecyNo { get; set; }
        public string CntContract_ProphecyDate { get; set; }
        public Nullable<short> CntContract_DayBeforeAlert { get; set; }
        public Nullable<int> SalCust_Si { get; set; }
        public Nullable<int> PurVendor_Si { get; set; }
        public Nullable<int> CntContract_SiOld { get; set; }
        public Nullable<int> CntSaleAgent_Si { get; set; }
        public string CntContract_ReceiptDate { get; set; }
        public string CntCustStatus_Cu { get; set; }
        public string CntContract_Note2 { get; set; }
        public string CntContract_SpecialNote { get; set; }
        public Nullable<double> CntContract_Prc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CntAlert> CntAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CntAttachment> CntAttachments { get; set; }
        public virtual CntGrp CntGrp { get; set; }
        public virtual CntTyp CntTyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CntGd> CntGds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CntPayment> CntPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CntReference> CntReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CntSrv> CntSrvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CntTask> CntTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CntTrack> CntTracks { get; set; }
    }
}
