//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CntGd
    {
        public int CntGds_Si { get; set; }
        public int CntContract_Si { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<int> InvUnt_Si { get; set; }
        public string CntGds_ArbitaryTp { get; set; }
        public Nullable<bool> CntGds_ArbitaryFlag { get; set; }
        public Nullable<double> CntGds_Quantity { get; set; }
        public Nullable<decimal> CntGds_UnitPrice { get; set; }
        public string CntGds_Comment { get; set; }
        public string CntGdsTx { get; set; }
    
        public virtual CntContract CntContract { get; set; }
    }
}
