//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CntLetter
    {
        public int CntLetter_si { get; set; }
        public Nullable<int> CntContract_Si { get; set; }
        public byte CntLetter_Type { get; set; }
        public string CntLetter_No1 { get; set; }
        public string CntLetter_No2 { get; set; }
        public string CntLetter_Subject { get; set; }
        public Nullable<System.DateTime> CntLetter_Date { get; set; }
        public byte[] CntLetter_File { get; set; }
        public string CntLetter_FileName { get; set; }
        public Nullable<int> CntLetter_FileSize { get; set; }
        public string CntLetter_FileType { get; set; }
        public Nullable<int> CntLetter_Sender_Si { get; set; }
        public Nullable<int> CntLetter_Reciver_Si { get; set; }
    }
}
