//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CntPaymentOpr
    {
        public int CntPaymentOpr_Si { get; set; }
        public string CntPaymentOpr_Tx { get; set; }
        public Nullable<decimal> CntPaymentOpr_DefaultValue { get; set; }
        public Nullable<byte> CntPaymentOpr_ValueTyp { get; set; }
        public Nullable<short> CntPaymentOpr_Typ { get; set; }
    }
}
