//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CntPayment
    {
        public int CntPayment_Si { get; set; }
        public int CntContract_Si { get; set; }
        public string CntPayment_Tx { get; set; }
        public string CntPayment_Date { get; set; }
        public Nullable<decimal> CntPayment_Price { get; set; }
        public Nullable<short> CntPayment_Typ { get; set; }
        public Nullable<bool> CntPayment_Ok { get; set; }
        public Nullable<byte> CntPayment_Method { get; set; }
    
        public virtual CntContract CntContract { get; set; }
    }
}
