//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CntTask
    {
        public int CntTask_Si { get; set; }
        public int CntContract_Si { get; set; }
        public Nullable<int> CntTask_SiParent { get; set; }
        public string CntTask_Tx { get; set; }
        public Nullable<int> CntTask_Progress { get; set; }
        public string CntTask_StartDate { get; set; }
        public string CntTask_EndDate { get; set; }
        public Nullable<byte> CntTask_Active { get; set; }
    
        public virtual CntContract CntContract { get; set; }
    }
}
