//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtbAc
    {
        public int CtbAcs_Si { get; set; }
        public string CtbAcs_Cu { get; set; }
        public string CtbAcs_Tp { get; set; }
        public Nullable<int> CtbAcs_SiParent { get; set; }
        public string CtbAcs_GrantScr { get; set; }
        public string CtbAcs_DenyScr { get; set; }
        public string CtbAcs_RevokeScr { get; set; }
        public string CtbAcs_Object { get; set; }
        public string CtbAcs_Action { get; set; }
    }
}
