//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtbAccDocDescFmt
    {
        public int SiAccDocDescFmt { get; set; }
        public string Grp { get; set; }
        public string CuAccDocDescFmt { get; set; }
        public string TpAccDocDescFmt { get; set; }
        public string DescFmtFarDebit { get; set; }
        public string DescFmtFarCredit { get; set; }
        public string DescFmtLatDebit { get; set; }
        public string DescFmtLatCredit { get; set; }
    }
}
