//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtbAccK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CtbAccK()
        {
            this.AccBudgets = new HashSet<AccBudget>();
            this.AccDDocs = new HashSet<AccDDoc>();
            this.CtbAccMs = new HashSet<CtbAccM>();
        }
    
        public int SiAccK { get; set; }
        public int SiAccGrp { get; set; }
        public string CuAcc { get; set; }
        public string TpAcc { get; set; }
        public System.DateTime CreateRec { get; set; }
        public string LoginName { get; set; }
        public string TpAcc2 { get; set; }
        public Nullable<int> CuAcc2 { get; set; }
        public Nullable<int> SiFather { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccBudget> AccBudgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccDDoc> AccDDocs { get; set; }
        public virtual CtbAccGrp CtbAccGrp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtbAccM> CtbAccMs { get; set; }
    }
}
