//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtbAddrsSwch
    {
        public int CtbAddrsSwch_Si { get; set; }
        public int CtbAddrs_Si { get; set; }
        public string CtbAddrsSwch_Tbl { get; set; }
        public int CtbAddrsSwch_Tbl_Si { get; set; }
        public Nullable<bool> CtbAddrsSwch_Active { get; set; }
    
        public virtual CtbAddr CtbAddr { get; set; }
    }
}
