//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtbCurncy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CtbCurncy()
        {
            this.AccDDocs = new HashSet<AccDDoc>();
            this.TrsRsrcs = new HashSet<TrsRsrc>();
        }
    
        public int CtbCurncy_Si { get; set; }
        public string CtbCurncy_Tp { get; set; }
        public string CtbCurncy_Fmt { get; set; }
        public Nullable<bool> CtbCurncy_Default { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccDDoc> AccDDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsRsrc> TrsRsrcs { get; set; }
    }
}
