//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtbOrgJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CtbOrgJob()
        {
            this.CtbOrgPsts = new HashSet<CtbOrgPst>();
            this.PerCmds = new HashSet<PerCmd>();
        }
    
        public int CtbOrgJob_Si { get; set; }
        public string CtbOrgJob_Cu { get; set; }
        public string CtbOrgJob_Tp { get; set; }
        public Nullable<short> CtbOrgJob_Prmt { get; set; }
        public Nullable<short> CtbOrgJob_Asgn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtbOrgPst> CtbOrgPsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerCmd> PerCmds { get; set; }
    }
}
