//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtbOption
    {
        public int SiOpt { get; set; }
        public string CuOpt { get; set; }
        public string GrpOpt { get; set; }
        public string TpOpt { get; set; }
        public Nullable<byte> Type { get; set; }
        public string OptValue { get; set; }
        public string Items { get; set; }
        public string UserGuide { get; set; }
        public string Description { get; set; }
        public string TpForm { get; set; }
        public Nullable<int> Row { get; set; }
    }
}
