//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtbProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CtbProject()
        {
            this.AccARqsts = new HashSet<AccARqst>();
            this.AccBudgets = new HashSet<AccBudget>();
            this.AccDDocs = new HashSet<AccDDoc>();
            this.BgtAssignToPrjs = new HashSet<BgtAssignToPrj>();
            this.CtbPrj2CtbAccM = new HashSet<CtbPrj2CtbAccM>();
            this.InvDocDs = new HashSet<InvDocD>();
            this.InvGdsAccPs = new HashSet<InvGdsAccP>();
            //this.InvInvts = new HashSet<InvInvt>();
            this.InvVchrCodeMaps = new HashSet<InvVchrCodeMap>();
            this.InvVchrDs = new HashSet<InvVchrD>();
            this.PerVchrDs = new HashSet<PerVchrD>();
            this.SalVchrDs = new HashSet<SalVchrD>();
            this.TrsAccs = new HashSet<TrsAcc>();
            this.TrsARqsts = new HashSet<TrsARqst>();
            this.TrsAsgns = new HashSet<TrsAsgn>();
            this.TrsDcAs = new HashSet<TrsDcA>();
            this.TrsVchrDs = new HashSet<TrsVchrD>();
        }
    
        public int SiProject { get; set; }
        public string CuProject { get; set; }
        public string TpProject { get; set; }
        public Nullable<int> SiFather { get; set; }
        public System.DateTime CreateRec { get; set; }
        public string LoginName { get; set; }
        public Nullable<int> SiHSrlDoc { get; set; }
        public string TpProject2 { get; set; }
        public string CuProject2 { get; set; }
        public string Ds_bondPrsnl { get; set; }
        public string Ds_bondPrsnlTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccARqst> AccARqsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccBudget> AccBudgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccDDoc> AccDDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BgtAssignToPrj> BgtAssignToPrjs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtbPrj2CtbAccM> CtbPrj2CtbAccM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDocD> InvDocDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvGdsAccP> InvGdsAccPs { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<InvInvt> InvInvts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvVchrCodeMap> InvVchrCodeMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvVchrD> InvVchrDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerVchrD> PerVchrDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalVchrD> SalVchrDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsAcc> TrsAccs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsARqst> TrsARqsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsAsgn> TrsAsgns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsDcA> TrsDcAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsVchrD> TrsVchrDs { get; set; }
    }
}
