//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        public int DateID { get; set; }
        public System.DateTime GDate { get; set; }
        public string PDate { get; set; }
        public int PYear { get; set; }
        public int PMonth { get; set; }
        public int PDay { get; set; }
        public string PMonthName { get; set; }
        public int PWeekOfYear { get; set; }
        public string PDayName { get; set; }
        public string PSeason { get; set; }
    }
}
