//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaraBarcode
    {
        public int FaraBarcode_Si { get; set; }
        public Nullable<int> PrcCount { get; set; }
        public Nullable<int> QtyCount { get; set; }
        public Nullable<int> GdsCount { get; set; }
        public Nullable<int> BatchCount { get; set; }
    }
}
