//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hatef22
    {
        public string کد_مشتری { get; set; }
        public string جنسیت { get; set; }
        public string نام { get; set; }
        public string نام_خانوادگی { get; set; }
        public int salcust_Si { get; set; }
        public string نوع_خط1 { get; set; }
        public string شماره_خط1 { get; set; }
        public string C2نوع_خط { get; set; }
        public string شماره_خط2 { get; set; }
        public string نوع_خط3 { get; set; }
        public string شماره_خط3 { get; set; }
        public string نوع_خط4 { get; set; }
        public string شماره_خط4 { get; set; }
        public string نوع_خط5 { get; set; }
        public string شماره_خط5 { get; set; }
        public string نوع_خط6 { get; set; }
        public string شماره_خط6 { get; set; }
        public string نوع_خط7 { get; set; }
        public string شماره_خط7 { get; set; }
        public string نوع_خط8 { get; set; }
        public string شماره_خط8 { get; set; }
        public string نوع_خط9 { get; set; }
        public string شماره_خط9 { get; set; }
        public string نوع_خط10 { get; set; }
        public string C10شماره_خط { get; set; }
        public string CtbAddrs_Addrs { get; set; }
        public string SalCountry_Tp { get; set; }
        public string SalProvince_Tp { get; set; }
        public string SalCity_Tp { get; set; }
        public string ادرس_به_عنوان { get; set; }
        public Nullable<long> count { get; set; }
        public string ادرس_2 { get; set; }
        public string ادرس_3 { get; set; }
        public string ادرس_4 { get; set; }
        public string ادرس_5 { get; set; }
        public string ادرس_6 { get; set; }
    }
}
