//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvBatchNumber
    {
        public int InvBatchNumber_Si { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<int> InvInvt_Si { get; set; }
        public Nullable<int> InvDocTyp_Si { get; set; }
        public string InvBatchNumber_Code { get; set; }
        public Nullable<int> InvDocD_Si { get; set; }
        public Nullable<int> InvDocH_Si { get; set; }
    
        public virtual InvDocD InvDocD { get; set; }
        public virtual InvDocTyp InvDocTyp { get; set; }
        public virtual InvGd InvGd { get; set; }
        //public virtual InvInvt InvInvt { get; set; }
    }
}
