//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCntH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvCntH()
        {
            this.InvCntDs = new HashSet<InvCntD>();
        }
    
        public int InvCntH_Si { get; set; }
        public string InvCntH_Ds { get; set; }
        public string InvCntH_Tp { get; set; }
        public int InvInvt_Si { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvCntD> InvCntDs { get; set; }
        //public virtual InvInvt InvInvt { get; set; }
    }
}
