//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvControlGdsD
    {
        public int InvControlGdsD_Si { get; set; }
        public Nullable<int> InvControlGds_Si { get; set; }
        public Nullable<double> InvControlGdsD_Qty { get; set; }
        public Nullable<int> InvControlGdsD_IsTention { get; set; }
        public Nullable<int> InvControlGdsD_Acpt { get; set; }
        public Nullable<bool> InvControlGdsD_Accept1 { get; set; }
        public Nullable<bool> InvControlGdsD_Accept2 { get; set; }
        public Nullable<bool> InvControlGdsD_AcceptInv1 { get; set; }
        public Nullable<bool> InvControlGdsD_AcceptInv2 { get; set; }
        public Nullable<double> InvControlGdsD_QtyAccept1 { get; set; }
        public Nullable<bool> InvControlGdsD_ISBack { get; set; }
        public Nullable<bool> InvControlGdsD_SndInv { get; set; }
    
        public virtual InvControlGd InvControlGd { get; set; }
    }
}
