//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCdngD
    {
        public int InvCdngD_Si { get; set; }
        public int InvCdngH_Si { get; set; }
        public string InvCdngD_Cu { get; set; }
        public string InvCdngD_Tp { get; set; }
        public Nullable<int> InvCdngD_Sqnc { get; set; }
        public string InvCdngD_UID { get; set; }
        public string InvCdngD_Lnk { get; set; }
    
        public virtual InvCdngH InvCdngH { get; set; }
    }
}
