//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCdngH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvCdngH()
        {
            this.InvCdngDs = new HashSet<InvCdngD>();
        }
    
        public int InvCdngH_Si { get; set; }
        public string InvCdngH_Tp { get; set; }
        public Nullable<int> InvCdngH_Sqnc { get; set; }
        public Nullable<int> InvCdngH_TpSqnc { get; set; }
        public bool InvCdngH_VsTp { get; set; }
        public bool InvCdngH_VsCu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvCdngD> InvCdngDs { get; set; }
    }
}
