//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCntrDocH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvCntrDocH()
        {
            this.InvCntrDocDs = new HashSet<InvCntrDocD>();
        }
    
        public int InvCntrDocH_Si { get; set; }
        public Nullable<int> InvCntrDocH_Cu { get; set; }
        public string InvCntrDocH_Tp { get; set; }
        public string InvCntrDocH_Ds { get; set; }
        public Nullable<short> InvCntrDocH_RfrncTyp { get; set; }
        public Nullable<int> InvInvt_Si { get; set; }
        public string InvCntrDocH_StmpCUs { get; set; }
        public Nullable<System.DateTime> InvCntrDocH_StmpCDT { get; set; }
        public string InvCntrDocH_StmpMUs { get; set; }
        public Nullable<System.DateTime> InvCntrDocH_StmpMDT { get; set; }
        public Nullable<int> InvTyp_Si { get; set; }
        public Nullable<int> InvCntrDocH_Sts { get; set; }
        public Nullable<int> PurVndr_Si { get; set; }
        public Nullable<int> InvControlGds_Si { get; set; }
        public Nullable<int> InvGdsEssential_Si { get; set; }
        public Nullable<bool> InvCntrDocH_Acp1 { get; set; }
        public Nullable<bool> InvCntrDocH_Acp2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvCntrDocD> InvCntrDocDs { get; set; }
    }
}
