//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDocH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvDocH()
        {
            this.AssReceiptHs = new HashSet<AssReceiptH>();
            this.InvDocAttaches = new HashSet<InvDocAttach>();
            this.InvDocDs = new HashSet<InvDocD>();
            this.PurInvcDs = new HashSet<PurInvcD>();
        }
    
        public int InvDocH_Si { get; set; }
        public Nullable<int> InvDocH_Cu { get; set; }
        public string InvDocH_Ds { get; set; }
        public int InvDocH_RfrncTyp { get; set; }
        public string InvDocH_Reference { get; set; }
        public bool InvDocH_Definite { get; set; }
        public byte InvDocH_Level { get; set; }
        public int InvDocTyp_Si { get; set; }
        public int InvInvt_Si { get; set; }
        public Nullable<int> PurVndr_Si { get; set; }
        public Nullable<int> PerPersonnel_Si { get; set; }
        public Nullable<int> AccM_Si { get; set; }
        public Nullable<int> InvInvt_Si_2 { get; set; }
        public Nullable<int> SalCust_Si { get; set; }
        public string InvDocH_Tp { get; set; }
        public Nullable<int> InvDocH_Si_2 { get; set; }
        public Nullable<int> InvDocH_Si_Parent { get; set; }
        public Nullable<int> SalInvcH_Si { get; set; }
        public Nullable<int> AccLM_Si_Hdr { get; set; }
        public Nullable<System.DateTime> InvDocH_Dm { get; set; }
        public Nullable<int> SalRetInvcH_Si { get; set; }
        public Nullable<int> InvDocH_Cu2 { get; set; }
        public Nullable<int> InvDocTmpH_Si { get; set; }
        public Nullable<int> InvVchrH_Id { get; set; }
        public Nullable<int> SalExportPrmH_Si { get; set; }
        public string InvDocH_ExpNo { get; set; }
        public Nullable<int> SalPreinvcH_Si { get; set; }
        public Nullable<int> InvDocH_Sts { get; set; }
        public string InvDocH_CuDoc { get; set; }
        public string InvDocH_StmpCUs { get; set; }
        public string InvDocH_Tp2 { get; set; }
        public Nullable<decimal> InvDocH_Prc_Inc { get; set; }
        public Nullable<decimal> InvDocH_Prc_Dec { get; set; }
        public Nullable<int> SalDrvr_Si { get; set; }
        public string BarNumber { get; set; }
        public string DescDriver { get; set; }
        public Nullable<bool> TempDoc { get; set; }
        public string TpCreator { get; set; }
        public string LoginName { get; set; }
        public string InvStatus { get; set; }
        public Nullable<int> InvDocDefinit_Si { get; set; }
        public string InvDocH_StsAcP107 { get; set; }
        public Nullable<bool> InvDocH_Qc { get; set; }
        public Nullable<bool> InvDocH_PM { get; set; }
        public Nullable<int> InvTyp_Si { get; set; }
        public Nullable<int> InvDocH_Good { get; set; }
        public Nullable<int> InvControlGds_Si { get; set; }
        public Nullable<int> InvExportPrmH_Si { get; set; }
        public Nullable<int> PerPrsnl_Si_1 { get; set; }
        public Nullable<int> PerPrsnl_Si_2 { get; set; }
        public Nullable<int> InvDocH_Reference_2 { get; set; }
        public Nullable<bool> InvDocH_SentAcc { get; set; }
        public string InvDocH_DlvLoc { get; set; }
        public string InvDocH_Drivername { get; set; }
        public Nullable<int> SalDriver_Si { get; set; }
        public string InvDocH_DlvBuy { get; set; }
        public string InvDocH_CarNo { get; set; }
        public Nullable<int> Invprint { get; set; }
        public string InvprintUser { get; set; }
        public Nullable<int> PurchaseSendID { get; set; }
        public Nullable<bool> SalFrom { get; set; }
        public Nullable<System.DateTime> InvDocH_StmpCDT { get; set; }
        public Nullable<bool> InvDocH_EstimatePrc { get; set; }
        public Nullable<int> InvDocH_Si_214 { get; set; }
        public Nullable<int> InvDocH_Si_104 { get; set; }
        public Nullable<int> InvRqstH_Si { get; set; }
        public Nullable<int> SiAccM { get; set; }
        public Nullable<bool> InvDocH_TrnsferDB { get; set; }
        public string InvDocH_TypeReceipte { get; set; }
        public string InvDocH_PurName { get; set; }
        public Nullable<int> SalTyp_Si { get; set; }
        public Nullable<int> Invdelivery_Si { get; set; }
        public Nullable<int> InvDocTyp_SiParent { get; set; }
        public Nullable<int> AccT_Si { get; set; }
        public string InvDocH_StmpTime { get; set; }
        public string InvDocH_StmpTimeEdit { get; set; }
        public Nullable<System.DateTime> InvDocH_StmpMDT { get; set; }
        public Nullable<int> SiCost { get; set; }
        public Nullable<int> CtbAddrs_Si { get; set; }
        public Nullable<int> InvOrderProduceH_Si { get; set; }
        public Nullable<decimal> InvDocH_SumTotal { get; set; }
        public Nullable<decimal> InvDocH_Total { get; set; }
        public Nullable<double> InvDocH_SumTotalBs { get; set; }
        public Nullable<double> InvDocH_TotalBs { get; set; }
        public string SalPreCu { get; set; }
        public string InvDocH_Desc { get; set; }
        public string InvDocH_Rcv { get; set; }
        public string InvDocH_Deliver { get; set; }
        public Nullable<double> InvDocH_Prc_Inc214 { get; set; }
        public Nullable<double> InvDocH_Prc_Dec214 { get; set; }
        public Nullable<double> InvDocH_CostOfRent { get; set; }
        public string InvDocH_CarType { get; set; }
        public string InvDocH_NumberPelak { get; set; }
        public Nullable<bool> InvDocH_AcceptNegahbani { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssReceiptH> AssReceiptHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDocAttach> InvDocAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDocD> InvDocDs { get; set; }
        public virtual InvDocTyp InvDocTyp { get; set; }
        //public virtual InvInvt InvInvt { get; set; }
        //public virtual PurVndr PurVndr { get; set; }
        public virtual SalInvcH SalInvcH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurInvcD> PurInvcDs { get; set; }
    }
}
