//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDocDefinit
    {
        public int InvDocDefinit_Si { get; set; }
        public string LoginName { get; set; }
        public string InvDocDefinit_Tp { get; set; }
        public Nullable<bool> EndLevel { get; set; }
        public Nullable<int> LevelNo { get; set; }
        public Nullable<bool> INV { get; set; }
        public Nullable<bool> SC { get; set; }
        public Nullable<bool> PM { get; set; }
        public Nullable<bool> QC { get; set; }
        public Nullable<bool> MI { get; set; }
    }
}
