//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDocVchr
    {
        public int InvDocVchr_Si { get; set; }
        public int InvDocH_Si { get; set; }
        public int AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> AccLC_Si { get; set; }
        public Nullable<int> AccLP_Si { get; set; }
        public string InvDocVchr_Tp { get; set; }
        public decimal InvDocVchr_Debit { get; set; }
        public decimal InvDocVchr_Credit { get; set; }
        public Nullable<decimal> InvDocVchr_DebitC { get; set; }
        public Nullable<decimal> InvDocVchr_CreditC { get; set; }
    }
}
