//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDocAccHelp
    {
        public int InvDocAccHelp_Si { get; set; }
        public string Bed_SiAccM { get; set; }
        public string Bed_SiAccT { get; set; }
        public string Bed_SiCost { get; set; }
        public string Bed_SiProject { get; set; }
        public string Bes_SiAccM { get; set; }
        public string Bes_SiAccT { get; set; }
        public string Bes_SiCost { get; set; }
        public string Bes_SiProject { get; set; }
        public string CuOption { get; set; }
        public Nullable<int> InvDoctyp_Si { get; set; }
    }
}
