//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDocAuto
    {
        public int InvInvt_Si_Source { get; set; }
        public int InvDocTyp_Si_Source { get; set; }
        public int InvInvt_Si_Dest { get; set; }
        public int InvDocTyp_Si_Dest { get; set; }
        public Nullable<bool> InvDocAuto_ExpandBOM { get; set; }
    
        public virtual InvDocTyp InvDocTyp { get; set; }
        public virtual InvDocTyp InvDocTyp1 { get; set; }
        //public virtual InvInvt InvInvt { get; set; }
        //public virtual InvInvt InvInvt1 { get; set; }
    }
}
