//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDocD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvDocD()
        {
            this.InvBatchNumbers = new HashSet<InvBatchNumber>();
        }
    
        public int InvDocD_Si { get; set; }
        public int InvDocH_Si { get; set; }
        public int InvGds_Si { get; set; }
        public int InvUnt_Si { get; set; }
        public Nullable<int> InvDocTmpD_Si { get; set; }
        public Nullable<int> CtbCost_Si { get; set; }
        public Nullable<int> CtbProject_Si { get; set; }
        public byte InvDocDSts_Si { get; set; }
        public Nullable<int> AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public double InvDocD_Qty { get; set; }
        public Nullable<double> InvDocD_Qty2 { get; set; }
        public decimal InvDocD_Price { get; set; }
        public decimal InvDocD_Total { get; set; }
        public string InvDocD_Tp { get; set; }
        public Nullable<int> InvGdsTyp_Si { get; set; }
        public Nullable<System.DateTime> InvDocD_ExpireDate { get; set; }
        public string InvDocD_SerialKey { get; set; }
        public string InvDocD_ExpNo { get; set; }
        public Nullable<decimal> InvDocD_PriceC { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<decimal> InvDocD_TotalC { get; set; }
        public Nullable<decimal> InvDocD_Price_2 { get; set; }
        public Nullable<int> SalExportPrmD_Si { get; set; }
        public string InvDocD_Desc { get; set; }
        public Nullable<int> InvOpr_Si { get; set; }
        public string InvOpr_Tp { get; set; }
        public Nullable<double> InvOpr_DefaultValue { get; set; }
        public Nullable<double> InvDocD_Prc_Inc { get; set; }
        public Nullable<double> InvDocD_Prc_Dec { get; set; }
        public Nullable<int> InvOpr_Si_2 { get; set; }
        public string InvOpr_Tp_2 { get; set; }
        public Nullable<double> InvOpr_DefaultValue_2 { get; set; }
        public Nullable<double> InvDocD_Prc_Inc_2 { get; set; }
        public Nullable<double> InvDocD_Prc_Dec_2 { get; set; }
        public Nullable<double> InvDocD_SumTotal { get; set; }
        public Nullable<decimal> InvDocD_PriceBs { get; set; }
        public Nullable<decimal> InvDocD_PriceCBs { get; set; }
        public Nullable<decimal> InvDocD_TotalBs { get; set; }
        public Nullable<decimal> InvDocD_TotalCBs { get; set; }
        public Nullable<int> InvDocD_Si_Parent { get; set; }
        public Nullable<int> InvDocRqst_Si { get; set; }
        public Nullable<int> InvOpr_Si_3 { get; set; }
        public string InvOpr_Tp_3 { get; set; }
        public Nullable<double> InvOpr_DefaultValue_3 { get; set; }
        public Nullable<double> InvDocD_Prc_Inc_3 { get; set; }
        public Nullable<double> InvDocD_Prc_Dec_3 { get; set; }
        public Nullable<int> InvControlGds_Cu { get; set; }
        public Nullable<double> InvDocD_FinalCostPrice { get; set; }
        public Nullable<System.DateTime> InvDocD_ExpirDateM { get; set; }
        public Nullable<int> PurchaseRequestID { get; set; }
        public Nullable<double> Remain { get; set; }
        public Nullable<int> PerPrsnl_Si { get; set; }
        public Nullable<int> InvRqstD_Si { get; set; }
        public Nullable<bool> Isallotment { get; set; }
        public Nullable<int> InvDocD_Si_2 { get; set; }
        public Nullable<int> InvDocD_Row { get; set; }
        public Nullable<int> SalPreInvcD_Si { get; set; }
        public Nullable<int> InvDocD_SumPrc_Dec { get; set; }
        public Nullable<int> InvDocD_SumPrc_Inc { get; set; }
        public Nullable<double> InvDocD_AllQty { get; set; }
        public Nullable<System.DateTime> InvDocD_DateProduce { get; set; }
        public string InvDocD_SerialNo { get; set; }
        public Nullable<System.DateTime> InvDocD_DateControl { get; set; }
        public Nullable<int> InvDocD_RiskResponse { get; set; }
        public Nullable<int> InvDocD_RiskIgnition { get; set; }
        public Nullable<int> InvDocD_Healthrisk { get; set; }
        public Nullable<int> InvDocD_SpecialRisk { get; set; }
        public Nullable<int> InvControlStatus_Si { get; set; }
        public Nullable<int> InvUnt_SiDest { get; set; }
        public Nullable<double> InvDocD_QtyDest { get; set; }
        public string InvDocD_SearchCode { get; set; }
        public Nullable<bool> InvDocD_GiftOk { get; set; }
        public Nullable<int> InvGiftDD_Si { get; set; }
        public Nullable<int> InvGiftD_Si { get; set; }
        public Nullable<double> InvDocD_Sal_Total { get; set; }
        public Nullable<double> SalTotal { get; set; }
        public Nullable<double> InvDocD_Sal_SumTotal { get; set; }
    
        public virtual CtbAccM CtbAccM { get; set; }
        public virtual CtbAccT CtbAccT { get; set; }
        public virtual CtbCost CtbCost { get; set; }
        public virtual CtbProject CtbProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvBatchNumber> InvBatchNumbers { get; set; }
        public virtual InvDocDSt InvDocDSt { get; set; }
        public virtual InvDocH InvDocH { get; set; }
        public virtual InvDocTmpD InvDocTmpD { get; set; }
        public virtual InvGd InvGd { get; set; }
        public virtual InvUnt InvUnt { get; set; }
    }
}
