//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDocTmpHAttach
    {
        public int InvDocTmpHAttach_Si { get; set; }
        public string InvDocTmpHAttach_Ds { get; set; }
        public string InvDocTmpHAttach_Tp { get; set; }
        public string InvDocTmpHAttach_FileName { get; set; }
        public byte[] InvDocTmpHAttach_File { get; set; }
        public Nullable<int> InvDocTmpH_Si { get; set; }
    
        public virtual InvDocTmpH InvDocTmpH { get; set; }
    }
}
