//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvExportPrmH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvExportPrmH()
        {
            this.InvExportPrmDs = new HashSet<InvExportPrmD>();
        }
    
        public int InvExportPrmH_Si { get; set; }
        public Nullable<int> InvExportPrmH_Cu { get; set; }
        public string InvExportPrmH_Tp { get; set; }
        public string InvExportPrmH_Ds { get; set; }
        public Nullable<short> InvExportPrmH_RfrncTyp { get; set; }
        public Nullable<int> InvInvt_Si { get; set; }
        public string InvExportPrmH_StmpCUs { get; set; }
        public Nullable<System.DateTime> InvExportPrmH_StmpCDT { get; set; }
        public string InvExportPrmH_StmpMUs { get; set; }
        public Nullable<System.DateTime> InvExportPrmH_StmpMDT { get; set; }
        public Nullable<int> InvTyp_Si { get; set; }
        public Nullable<int> InvExportPrmH_Sts { get; set; }
        public Nullable<int> PurVndr_Si { get; set; }
        public string InvExportPrmH_No { get; set; }
        public string InvExportPrmH_Driver { get; set; }
        public string InvExportPrmH_Car { get; set; }
        public string InvExportPrmH_Dest { get; set; }
        public string InvExportPrmH_ExtCus { get; set; }
        public string InvExportPrmH_Tahvil { get; set; }
        public string DescDriver { get; set; }
        public string BarNumber { get; set; }
        public string InvExportPrmH_DlvBuy { get; set; }
        public string InvExportPrmH_CarNo { get; set; }
        public Nullable<int> PerPrsnl_Si_1 { get; set; }
        public Nullable<int> PerPrsnl_Si_2 { get; set; }
        public Nullable<int> InvExportPrmH_Good { get; set; }
        public Nullable<int> SalDriver_Si { get; set; }
        public Nullable<bool> InvExportPrmH_Lock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvExportPrmD> InvExportPrmDs { get; set; }
    }
}
