//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvGdsGrant
    {
        public int InvGdsGrant_Si { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<int> SalCust_Si { get; set; }
        public Nullable<int> SalIntrmd_Si { get; set; }
        public Nullable<double> InvGdsGrantCust_Qty { get; set; }
        public Nullable<double> InvGdsGrantIntrmd_Qty { get; set; }
        public string InvGdsGrant_Ds { get; set; }
    
        public virtual InvGd InvGd { get; set; }
        public virtual SalCust SalCust { get; set; }
        public virtual SalIntrmd SalIntrmd { get; set; }
    }
}
