//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvGdsToGd
    {
        public int InvGdsToGds_Si { get; set; }
        public Nullable<int> InvGds_Si_M { get; set; }
        public Nullable<int> InvGds_Si_D { get; set; }
        public Nullable<double> InvGdsToGds_Qty { get; set; }
        public Nullable<int> InvInvt_Si { get; set; }
        public Nullable<int> SiFather { get; set; }
    
        //public virtual InvInvt InvInvt { get; set; }
    }
}
