//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvGd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvGd()
        {
            this.InvBatchNumbers = new HashSet<InvBatchNumber>();
            this.InvCntBatchDs = new HashSet<InvCntBatchD>();
            this.InvCntDs = new HashSet<InvCntD>();
            this.InvDocDs = new HashSet<InvDocD>();
            this.InvDrctCnsuDs = new HashSet<InvDrctCnsuD>();
            this.InvGdsAccCs = new HashSet<InvGdsAccC>();
            this.InvGdsAccPs = new HashSet<InvGdsAccP>();
            this.InvGdsGrants = new HashSet<InvGdsGrant>();
            this.InvGdsRepGds = new HashSet<InvGdsRepGd>();
            this.InvGdsToInvs = new HashSet<InvGdsToInv>();
            this.PrdcBOMs = new HashSet<PrdcBOM>();
            this.PrdcBOMDs = new HashSet<PrdcBOMD>();
            this.PrdcTraceDInfoes = new HashSet<PrdcTraceDInfo>();
            this.PrdcTraceDMaterials = new HashSet<PrdcTraceDMaterial>();
            this.PrdcWorkOrderDInfoes = new HashSet<PrdcWorkOrderDInfo>();
            this.PrdcWorkOrderDMaterials = new HashSet<PrdcWorkOrderDMaterial>();
            this.PurEnqries = new HashSet<PurEnqry>();
            this.PurInvcDs = new HashSet<PurInvcD>();
            this.PurOrdrs = new HashSet<PurOrdr>();
            this.PurRqstDs = new HashSet<PurRqstD>();
            this.SalContractDs = new HashSet<SalContractD>();
            this.SalDclrPrcDs = new HashSet<SalDclrPrcD>();
            this.SalePreInvoiceDetails = new HashSet<SalePreInvoiceDetail>();
            this.SalGdsAccs = new HashSet<SalGdsAcc>();
            this.SalGdsRetAccs = new HashSet<SalGdsRetAcc>();
            this.SalInvcDs = new HashSet<SalInvcD>();
            this.SalInvcDSrls = new HashSet<SalInvcDSrl>();
            this.SalPreInvcDs = new HashSet<SalPreInvcD>();
            this.SalPromotionDs = new HashSet<SalPromotionD>();
            this.SalRequestDs = new HashSet<SalRequestD>();
            this.SalRetInvcDs = new HashSet<SalRetInvcD>();
            this.SalRetInvcDSrls = new HashSet<SalRetInvcDSrl>();
        }
    
        public int InvGds_Si { get; set; }
        public string InvGds_Cu { get; set; }
        public string InvGds_Tp { get; set; }
        public string InvGds_Cm { get; set; }
        public int InvUnt_Si { get; set; }
        public int InvGdsGrp_Si { get; set; }
        public string InvGds_TechNo { get; set; }
        public double InvGds_QtyReal { get; set; }
        public double InvGds_QtyVirtual { get; set; }
        public double InvGds_QtyMin { get; set; }
        public double InvGds_QtyMax { get; set; }
        public double InvGds_QtySafe { get; set; }
        public bool InvGds_PrdGds { get; set; }
        public string InvGds_LName { get; set; }
        public Nullable<int> InvGdsICntry_Si { get; set; }
        public Nullable<int> InvGdsICratr_Si { get; set; }
        public Nullable<decimal> InvGds_StdPrc { get; set; }
        public Nullable<decimal> InvGds_PurchasePrc { get; set; }
        public Nullable<int> InvUnt_Si_Sale { get; set; }
        public Nullable<decimal> InvGds_SalePrc { get; set; }
        public Nullable<int> InvUnt_Count { get; set; }
        public Nullable<int> InvGdsStatus_Si { get; set; }
        public Nullable<int> Siaccm { get; set; }
        public string invGdsGrp_SiParent { get; set; }
        public Nullable<int> PurGdsGrp_Si { get; set; }
        public Nullable<decimal> InvGds_PurchasePrcC { get; set; }
        public Nullable<System.DateTime> InvGds_DateBirth { get; set; }
        public Nullable<bool> InvGds_Active { get; set; }
        public Nullable<double> InvGds_QtySale { get; set; }
        public Nullable<bool> InvGds_ActiveSale { get; set; }
        public Nullable<bool> InvGds_ActiveSerial { get; set; }
        public Nullable<double> InvGds_QtyMinOrd { get; set; }
        public Nullable<double> InvGds_QtyBestInWay { get; set; }
        public Nullable<int> InvGds_CountdayInWay { get; set; }
        public Nullable<int> SiAccT { get; set; }
        public Nullable<bool> ShowInWeb { get; set; }
        public Nullable<int> InvbasketGds_Si { get; set; }
        public Nullable<int> InvGdsGrp_Si_2 { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<int> Plane_No { get; set; }
        public Nullable<int> Employer_No { get; set; }
        public Nullable<double> InvGds_burden { get; set; }
        public Nullable<int> InvGds_height { get; set; }
        public Nullable<int> InvGds_width { get; set; }
        public Nullable<int> InvGds_length { get; set; }
        public Nullable<int> InvGds_ForOrInter { get; set; }
        public string InvGds_Seri { get; set; }
        public string InvGds_consumable { get; set; }
        public Nullable<int> InvGds_MonthNO { get; set; }
        public string InvGds_IdTechnical { get; set; }
        public Nullable<int> InvSeating_Si { get; set; }
        public Nullable<int> InvStorageSpace_Si { get; set; }
        public Nullable<int> InvTemperature_Si { get; set; }
        public Nullable<int> InvLight_Si { get; set; }
        public Nullable<int> InvHumidity_Si { get; set; }
        public Nullable<int> InvPackageType_Si { get; set; }
        public Nullable<int> InvPhysicalState_Si { get; set; }
        public Nullable<double> InvLayoutRow { get; set; }
        public Nullable<double> InvLayoutCount { get; set; }
        public Nullable<double> Invpalletweight { get; set; }
        public Nullable<double> InvContainerweight { get; set; }
        public Nullable<double> InvContainer { get; set; }
        public Nullable<double> InvPallet { get; set; }
        public string InvGds_RiskResponse { get; set; }
        public string InvGds_Healthrisk { get; set; }
        public string InvGds_SpecialRisk { get; set; }
        public string InvGds_RiskIgnition { get; set; }
        public Nullable<int> InvUnt_Si_Dest { get; set; }
        public Nullable<double> InvGds_Coefficient { get; set; }
        public Nullable<double> InvGds_QtyRealDest { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> InvGds_PromotionActive { get; set; }
        public Nullable<double> InvGds_Bulk { get; set; }
        public Nullable<double> InvGds_PromoQty { get; set; }
        public Nullable<int> InvGdsRiskResponse_Si { get; set; }
        public Nullable<int> InvGdsHealthrisk_Si { get; set; }
        public Nullable<int> InvGdsSpecialRisk_Si { get; set; }
        public Nullable<int> InvGdsRiskIgnition_Si { get; set; }
        public Nullable<int> Invpalletweight_Si { get; set; }
        public Nullable<int> InvContainerweight_Si { get; set; }
        public Nullable<double> InvGds_PrcConsumer { get; set; }
        public Nullable<int> InvGdsSrvType_Si { get; set; }
        public Nullable<int> SiAccT_Doc { get; set; }
        public Nullable<double> InvGds_PromoQtyCalc { get; set; }
    
        public virtual InvbasketGd InvbasketGd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvBatchNumber> InvBatchNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvCntBatchD> InvCntBatchDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvCntD> InvCntDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDocD> InvDocDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDrctCnsuD> InvDrctCnsuDs { get; set; }
        public virtual InvGdsGrp InvGdsGrp { get; set; }
        public virtual InvGdsICntry InvGdsICntry { get; set; }
        public virtual InvGdsICratr InvGdsICratr { get; set; }
        public virtual InvGdsStatu InvGdsStatu { get; set; }
        public virtual InvUnt InvUnt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvGdsAccC> InvGdsAccCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvGdsAccP> InvGdsAccPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvGdsGrant> InvGdsGrants { get; set; }
        public virtual InvGdsPhoto InvGdsPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvGdsRepGd> InvGdsRepGds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvGdsToInv> InvGdsToInvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdcBOM> PrdcBOMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdcBOMD> PrdcBOMDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdcTraceDInfo> PrdcTraceDInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdcTraceDMaterial> PrdcTraceDMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdcWorkOrderDInfo> PrdcWorkOrderDInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdcWorkOrderDMaterial> PrdcWorkOrderDMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurEnqry> PurEnqries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurInvcD> PurInvcDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurOrdr> PurOrdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurRqstD> PurRqstDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalContractD> SalContractDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalDclrPrcD> SalDclrPrcDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalePreInvoiceDetail> SalePreInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalGdsAcc> SalGdsAccs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalGdsRetAcc> SalGdsRetAccs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalInvcD> SalInvcDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalInvcDSrl> SalInvcDSrls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcD> SalPreInvcDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPromotionD> SalPromotionDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalRequestD> SalRequestDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalRetInvcD> SalRetInvcDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalRetInvcDSrl> SalRetInvcDSrls { get; set; }
    }
}
