//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvGdsPhoto
    {
        public int InvGds_Si { get; set; }
        public byte[] InvGdsPhoto_Image { get; set; }
        public byte[] InvGdsPhoto_Icon { get; set; }
    
        public virtual InvGd InvGd { get; set; }
    }
}
