//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvRqstH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvRqstH()
        {
            this.InvRqstDs = new HashSet<InvRqstD>();
        }
    
        public int InvRqstH_Si { get; set; }
        public Nullable<int> InvRqstH_Cu { get; set; }
        public Nullable<System.DateTime> InvRqstH_DT { get; set; }
        public string InvRqstH_Tp { get; set; }
        public byte InvRqstTyp_Si { get; set; }
        public Nullable<int> InvDocH_Si { get; set; }
        public Nullable<int> PurReqstH_Si { get; set; }
        public Nullable<int> InvRqstH_CuPur { get; set; }
        public Nullable<int> invinvt_si { get; set; }
        public Nullable<bool> InvRqstH_Lock { get; set; }
        public string InvRqstH_StmpTimeEdit { get; set; }
        public string InvRqstH_StmpTime { get; set; }
        public string InvRqstH_StmpCUs { get; set; }
        public Nullable<System.DateTime> InvRqstH_StmpCDT { get; set; }
        public string InvRqstH_StmpMUs { get; set; }
        public Nullable<System.DateTime> InvRqstH_StmpMDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRqstD> InvRqstDs { get; set; }
    }
}
