//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvUsr
    {
        public int InvUsr_Si { get; set; }
        public string InvUsr_LgnName { get; set; }
        public string InvUsr_Tp { get; set; }
        public Nullable<bool> InvUsr_AcsMny { get; set; }
        public Nullable<bool> InvUsr_AcsQty { get; set; }
        public Nullable<bool> InvUsr_Account { get; set; }
        public Nullable<bool> InvUsr_AcsM { get; set; }
        public Nullable<bool> InvUsr_AcsT { get; set; }
        public Nullable<bool> InvUsr_AcsC { get; set; }
        public Nullable<bool> InvUsr_AcsP { get; set; }
        public Nullable<int> InvUsr_NumDay { get; set; }
        public Nullable<bool> InvUsr_AcsSale { get; set; }
        public Nullable<bool> InvUsr_showQtyInPre { get; set; }
    }
}
