//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvUntDest
    {
        public int InvUntDest_Si { get; set; }
        public Nullable<int> InvUnt_Si { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<double> InvUntDest_Coefficient { get; set; }
    }
}
