//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPurQry
    {
        public int PurQry_Si { get; set; }
        public string PurQry_Dt { get; set; }
        public Nullable<double> PurQry_Discount { get; set; }
        public Nullable<decimal> PurQry_LastPrice { get; set; }
        public Nullable<decimal> PurQry_Price { get; set; }
        public string PurQry_Cond { get; set; }
        public string PurQry_ReciptDt { get; set; }
        public string PurQry_Kind { get; set; }
        public Nullable<int> PurVndr_Si { get; set; }
        public Nullable<int> PurRqstH_Si { get; set; }
        public string PurQry_Comment { get; set; }
        public string PurQry_EndDt { get; set; }
        public string PurQry_Cu { get; set; }
    }
}
