//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPurLvlD
    {
        public int PurLvlD_Si { get; set; }
        public string PurLvlD_Cu { get; set; }
        public Nullable<int> KPurLvlH_Si { get; set; }
    }
}
