//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPurBuyH
    {
        public int PurBuyH_Si { get; set; }
        public string PurBuyH_Cu { get; set; }
        public string PurBuyH_Cm { get; set; }
        public Nullable<System.DateTime> PurBuyH_Dt { get; set; }
        public string PurBuyH_VnFno { get; set; }
        public Nullable<System.DateTime> PurBuyH_FaDt { get; set; }
        public Nullable<int> PurOrdrH_Si { get; set; }
    }
}
