//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPurHi
    {
        public int PurHis_Si { get; set; }
        public string PurHis_Cu { get; set; }
        public Nullable<System.DateTime> PurHis_Dt { get; set; }
        public string PurHis_Ds { get; set; }
        public string PurHis_User { get; set; }
        public Nullable<int> PurLvl_Si { get; set; }
        public Nullable<int> PurRqstH_Si { get; set; }
        public Nullable<int> PurHis_UserLvl { get; set; }
    
        public virtual KPurHi KPurHis1 { get; set; }
        public virtual KPurHi KPurHi1 { get; set; }
    }
}
