//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Per_PW1100
    {
        public int PerPyrlPeriod_Si { get; set; }
        public string CARD { get; set; }
        public string PERSNL { get; set; }
        public string NAME { get; set; }
        public string EDARE { get; set; }
        public string SHIFT { get; set; }
        public string HOZOUR { get; set; }
        public string DIRKARD { get; set; }
        public string TAJILIN { get; set; }
        public string TAJILOUT { get; set; }
        public string KASRKAR { get; set; }
        public string SHABKARI { get; set; }
        public string EZAF { get; set; }
        public string EZAFT { get; set; }
        public string EZAFF { get; set; }
        public string PARAM1 { get; set; }
        public string PARAM2 { get; set; }
        public string SERVICE { get; set; }
        public string MORS1 { get; set; }
        public string MORS2 { get; set; }
        public string MORS3 { get; set; }
        public string MORS4 { get; set; }
        public string MARS1 { get; set; }
        public string MARS2 { get; set; }
        public string MARS3 { get; set; }
        public string MARS4 { get; set; }
        public string MOR5 { get; set; }
        public string MOR6 { get; set; }
        public string MOR7 { get; set; }
        public string MOR8 { get; set; }
        public string MOR9 { get; set; }
        public string MOR10 { get; set; }
        public string MOR11 { get; set; }
        public string MOR12 { get; set; }
        public string MOR13 { get; set; }
        public string MOR14 { get; set; }
        public string MOR15 { get; set; }
        public string MAR5 { get; set; }
        public string MAR6 { get; set; }
        public string MAR7 { get; set; }
        public string MAR8 { get; set; }
        public string PARAM3 { get; set; }
        public string PARAM4 { get; set; }
        public string KARKARD { get; set; }
        public string GEIBAT { get; set; }
        public string EZAFKH { get; set; }
    }
}
