//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerCmdOpr
    {
        public int PerCmdOpr_Si { get; set; }
        public int PerCmd_Si { get; set; }
        public string PerCmdOpr_Cu { get; set; }
        public string PerCmdOpr_Tp { get; set; }
        public int PerCmdOpr_Seq { get; set; }
        public string PerCmdOpr_If { get; set; }
        public string PerCmdOpr_Calc { get; set; }
        public Nullable<bool> PerCmdOpr_IsMovagh { get; set; }
    
        public virtual PerCmd PerCmd { get; set; }
    }
}
