//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerDskTaxPrimeH
    {
        public int PerDskTaxPrimeH_Si { get; set; }
        public string PerDskTaxPrimeH_Cu { get; set; }
        public string PerDskTaxPrimeH_Tp { get; set; }
        public string Description { get; set; }
    }
}
