//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerLoanTyp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerLoanTyp()
        {
            this.PerLoans = new HashSet<PerLoan>();
        }
    
        public int PerLoanTyp_Si { get; set; }
        public string PerLoanTyp_Cu { get; set; }
        public string PerLoanTyp_Tp { get; set; }
        public Nullable<int> AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerLoan> PerLoans { get; set; }
    }
}
