//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerLoanRqst
    {
        public int PerLoanRqst_Si { get; set; }
        public int PerPrsnl_Si { get; set; }
        public int PerLoanTyp_Si { get; set; }
        public Nullable<int> PerLoanRqst_Cu { get; set; }
        public string PerLoanRqst_Tp { get; set; }
        public string PerLoanRqst_Ds { get; set; }
        public Nullable<decimal> PerLoanRqst_Rem { get; set; }
        public decimal PerLoanRqst_Price { get; set; }
        public Nullable<bool> PerLoanRqst_Accept { get; set; }
        public Nullable<int> PerLoan_Si { get; set; }
        public string PerLoanRqst_UserInsert { get; set; }
        public string PerLoanRqst_UserAccept { get; set; }
        public string PerLoanRqst_DateInsert { get; set; }
        public string PerLoanRqst_DateAccept { get; set; }
        public string PerLoanRqst_DescAccept { get; set; }
        public Nullable<int> PerLoanRqst_Countpayment { get; set; }
    }
}
