//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerLoanGivBak
    {
        public int PerLoanGivBak_Si { get; set; }
        public int PerLoan_Si { get; set; }
        public string PerLoanGivBak_Ds { get; set; }
        public decimal PerLoanGivBak_Price { get; set; }
        public string PerLoanGivBak_Tp { get; set; }
        public Nullable<int> PerPyrlPeriod_Si { get; set; }
        public Nullable<bool> IsVoucher { get; set; }
        public Nullable<int> SiHDoc { get; set; }
    
        public virtual PerLoan PerLoan { get; set; }
        public virtual PerPyrlPeriod PerPyrlPeriod { get; set; }
    }
}
