//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerMamor
    {
        public int PerMamor_Si { get; set; }
        public string PerMamor_Ds { get; set; }
        public Nullable<int> PerPrsnl_Si { get; set; }
        public string PerMamor_MFDs { get; set; }
        public string PerMamor_MLDs { get; set; }
        public string PerMamor_City { get; set; }
        public string PerMamor_Desc { get; set; }
        public Nullable<int> PerHaml_Si { get; set; }
        public Nullable<int> PerMamor_OnewayTicket { get; set; }
        public Nullable<double> PerMamor_KmGo { get; set; }
        public Nullable<double> PerMamor_KmReturn { get; set; }
        public Nullable<double> PerMamor_KmSum { get; set; }
        public Nullable<System.DateTime> PerMamor_TimeGo { get; set; }
        public Nullable<System.DateTime> PerMamor_TimeReturn { get; set; }
        public string PerMamor_MFWeek { get; set; }
        public string PerMamor_MLWeek { get; set; }
        public Nullable<int> PerMamor_Tashilat { get; set; }
        public string PerMamor_TashilFrDs { get; set; }
        public string PerMamor_TashilToDs { get; set; }
        public Nullable<short> PerMamor_Day { get; set; }
        public Nullable<short> PerMamor_Time { get; set; }
        public Nullable<int> PerMamorPlace_Si { get; set; }
        public Nullable<int> PerMamor_NightCount { get; set; }
        public Nullable<int> PerMamor_BrkFCount { get; set; }
        public Nullable<int> PerMamor_NaharCount { get; set; }
        public Nullable<int> PerMamor_DnCount { get; set; }
        public Nullable<int> PerAirLine_Si { get; set; }
        public Nullable<double> PerMamor_Price { get; set; }
    }
}
