//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerPaySummery
    {
        public int PerPaySummery_Si { get; set; }
        public Nullable<int> PerPayerH_Si { get; set; }
        public Nullable<int> PerPyrlPeriod_Si { get; set; }
        public Nullable<double> PerPaySummery_Sum1Now { get; set; }
        public Nullable<double> PerPaySummery_Sum2Now { get; set; }
        public Nullable<double> PerPaySummery_Tax { get; set; }
        public Nullable<double> PerPaySummery_Sum1Pre { get; set; }
        public Nullable<double> PerPaySummery_Sum2Pre { get; set; }
        public Nullable<double> PerPaySummery_Penalty1 { get; set; }
        public Nullable<double> PerPaySummery_Penalty1Pre { get; set; }
        public Nullable<double> PerPaySummery_Penalty2 { get; set; }
        public Nullable<double> PerPaySummery_PenaltyPre { get; set; }
        public Nullable<double> PerPaySummery_TaxDebitNow { get; set; }
        public Nullable<double> PerPaySummery_TaxDebitPre { get; set; }
        public string PerPaySummery_DateInsu { get; set; }
        public Nullable<int> PerPaySummery_NumPer { get; set; }
        public Nullable<int> PerPaySummery_ForNumPer { get; set; }
        public string PerPaySummery_PayType { get; set; }
        public Nullable<double> PerPaySummery_SumTaxNow { get; set; }
        public Nullable<double> PerPaySummery_SumTaxPre { get; set; }
        public string PerPaySummery_ChpDate { get; set; }
        public string PerPaySummery_ChpAccNo { get; set; }
        public string PerPaySummery_ChpBankName { get; set; }
        public string PerPaySummery_ChpBrnchName { get; set; }
        public Nullable<double> PerPaySummery_TaxPay { get; set; }
        public Nullable<int> PerPaySummery_PayTypIn { get; set; }
        public Nullable<int> PerTaxGrp_Si { get; set; }
        public Nullable<int> CtbBank_Si { get; set; }
        public string PerPaySummery_ChpNo { get; set; }
        public Nullable<int> PerPaidType_Si { get; set; }
        public Nullable<decimal> PerPaySummery_CheqPrice { get; set; }
        public string PerPaySummery_PayDate { get; set; }
        public Nullable<int> PerPaymentType_Si { get; set; }
    }
}
