//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerPrsnlHstryFml
    {
        public int PerPrsnlHstryFml_Si { get; set; }
        public string PerPrsnlHstryFml_Tp { get; set; }
        public string PerPrsnlHstryFml_Typ { get; set; }
        public Nullable<System.DateTime> PerPrsnlHstryFml_DateBrth { get; set; }
        public string PerPrsnlHstryFml_Madrak { get; set; }
        public Nullable<int> PerPrsnl_Si { get; set; }
    }
}
