//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerPrsnlD
    {
        public int PerPrsnl_Si { get; set; }
        public string PerPrsnlD_Cm { get; set; }
        public string PerPrsnlD_PName { get; set; }
        public string PerPrsnlD_IDNo { get; set; }
        public string PerPrsnlD_IDLoc { get; set; }
        public string PerPrsnlD_IDDte { get; set; }
        public string PerPrsnlD_BrtDte { get; set; }
        public Nullable<bool> PerPrsnlD_Marid { get; set; }
        public Nullable<byte> PerPrsnlD_Chld { get; set; }
        public string PerPrsnlD_Sldr { get; set; }
        public string PerPrsnlD_Edu { get; set; }
        public string PerPrsnlD_EmpDte { get; set; }
        public string PerPrsnlD_WrkBgnDte { get; set; }
        public string PerPrsnlD_WrkEndDte { get; set; }
        public Nullable<byte> PerPrsnlD_Sex { get; set; }
        public Nullable<bool> PerPrsnlD_Frgn { get; set; }
        public string PerPrsnlD_EMail { get; set; }
        public string PerPrsnlD_URL { get; set; }
        public string PerPrsnlD_Tel1 { get; set; }
        public string PerPrsnlD_Tel2 { get; set; }
        public string PerPrsnlD_Fax { get; set; }
        public string PerPrsnlD_Adrs { get; set; }
        public byte[] PerPrsnlD_Photo { get; set; }
        public string PerPrsnlD_Bnk_Name { get; set; }
        public string PerPrsnlD_Bnk_Brnch { get; set; }
        public string PerPrsnlD_Bnk_AccNo { get; set; }
        public string PerPrsnlD_Bnk_AccTyp { get; set; }
        public string Insrnc_No { get; set; }
        public string Insrnc_FName { get; set; }
        public string Insrnc_LName { get; set; }
        public string Insrnc_DName { get; set; }
        public string Insrnc_IDNO { get; set; }
        public string Insrnc_IDPLC { get; set; }
        public string Insrnc_NAT { get; set; }
        public string Insrnc_OCP { get; set; }
        public Nullable<System.DateTime> PerPrsnlD_BuyBak { get; set; }
        public Nullable<byte> PerInsrncGrp_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public string PerPrsnlID_NatCode { get; set; }
        public string Insrnc_OCPCode { get; set; }
        public string PerPrsnlD_Major { get; set; }
        public string PerPrsnlD_UniverCity { get; set; }
        public Nullable<bool> PerPrsnl_NotBimeh { get; set; }
        public Nullable<int> PerLoc_Si { get; set; }
        public Nullable<int> BankAccountNO { get; set; }
        public string PerPrsnlD_JobType { get; set; }
        public string PerPrsnlID_PassportCode { get; set; }
        public Nullable<int> PerPrsnlD_HistoryJob { get; set; }
        public string PerPrsnlD_PostCode { get; set; }
        public string Insrnc_OCPTp { get; set; }
        public Nullable<int> PerTaxGrp_Si { get; set; }
        public Nullable<int> PereEducate_Si { get; set; }
        public Nullable<int> PerMajor_Si { get; set; }
        public Nullable<int> PerExempt_Si { get; set; }
        public Nullable<int> PerInterNational_Si { get; set; }
        public Nullable<int> PerPrsnlD_InsureType { get; set; }
        public string PerPrsnlD_Country { get; set; }
        public string PerPrsnlD_PlcBrth { get; set; }
        public string PerPrsnlD_Religion { get; set; }
        public string PerPrsnlD_liberal { get; set; }
        public string PerPrsnlD_TypJob { get; set; }
        public string PerPrsnlD_EmpStatus { get; set; }
        public string PerPrsnlD_TimeInwar { get; set; }
        public string PerPrsnlD_TimeWorkAcc { get; set; }
        public string PerPrsnlD_JobPlace { get; set; }
        public Nullable<int> PerPrsnlD_GroupCode { get; set; }
        public string PerPrsnlD_IdentityJob { get; set; }
        public Nullable<int> PerPrsnlD_Expert { get; set; }
        public Nullable<int> PerPrsnlD_Home { get; set; }
        public string PerPrsnlD_HardCode { get; set; }
        public Nullable<int> PerInsrnPromise_Si { get; set; }
        public Nullable<int> PerPrsnlD_TypeCmd { get; set; }
        public Nullable<int> PerPrsnlD_SponsorShipNo { get; set; }
        public string PerPrsnlD_Post { get; set; }
        public string PerPrsnlD_PostName { get; set; }
        public string PerPrsnlD_placeOffice { get; set; }
        public Nullable<int> PerPlaceOfficeStatus_Si { get; set; }
        public Nullable<int> PeremployeeStatus_Si { get; set; }
        public Nullable<int> PerPaidType_Si { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<int> PerVehicleFlag_Si { get; set; }
        public Nullable<int> PerFurnitureFlag_Si { get; set; }
        public Nullable<int> PerCurency_Si { get; set; }
        public Nullable<int> PerContractTyp_Si { get; set; }
        public string PerInsurnce_Name { get; set; }
        public string PerPrsnlD_StmpCUs { get; set; }
        public Nullable<System.DateTime> PerPrsnlD_StmpCDT { get; set; }
        public string PerPrsnlD_StmpMUs { get; set; }
        public Nullable<System.DateTime> PerPrsnlD_StmpMDT { get; set; }
        public string PerPrsnlD_StmpTime { get; set; }
        public string PerPrsnlD_StmpTimeEdit { get; set; }
        public Nullable<int> CtbOrgJob_Si { get; set; }
        public string PerPrsnlD_AllReligion { get; set; }
        public string PerPrsnlD_Martyr { get; set; }
        public Nullable<bool> PerPrsnlD_underSposerShip { get; set; }
        public string PerPrsnlD_meliMain { get; set; }
        public string PerPrsnlD_SerialCodeMeli { get; set; }
        public string PerPrsnlD_ValidDateCodeMeli { get; set; }
        public string PerPrsnlD_SerialNumber { get; set; }
        public string PerPrsnlD_PasPortNumber { get; set; }
        public string PerPrsnlD_ValidDatePassNumber { get; set; }
        public Nullable<int> PerWorkPlaceGrade_Si { get; set; }
        public Nullable<int> PerWorkPlace_Si { get; set; }
        public string PerPrsnlD_Ostan { get; set; }
        public string PerPrsnlD_Sharestan { get; set; }
        public string PerPrsnlD_Bnk_AccNo2 { get; set; }
        public Nullable<double> PerPrsnlD_Price { get; set; }
    
        public virtual CtbAccT CtbAccT { get; set; }
        public virtual PerInsrncGrp PerInsrncGrp { get; set; }
    }
}
