//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerPayrollDelayed
    {
        public int PerPayrollDelayed_Si { get; set; }
        public int PerPrsnl_Si { get; set; }
        public int PerPyrlPeriod_Si { get; set; }
        public string PerPayrollDelayed_Cu { get; set; }
        public string PerPayrollDelayed_Tp { get; set; }
        public string PerPayrollDelayed_If { get; set; }
        public string PerPayrollDelayed_Calc { get; set; }
        public Nullable<decimal> PerPayrollDelayed_Value { get; set; }
        public Nullable<int> PerPayrollDelayed_Seq { get; set; }
        public Nullable<int> PerCmd_Si { get; set; }
    }
}
