//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerPrsnlAttach
    {
        public int PerPrsnlAttach_Si { get; set; }
        public string PerPrsnlAttach_Ds { get; set; }
        public string PerPrsnlAttach_Tp { get; set; }
        public string PerPrsnlAttach_FileName { get; set; }
        public byte[] PerPrsnlAttach_File { get; set; }
        public Nullable<int> PerPrsnl_Si { get; set; }
    
        public virtual PerPrsnl PerPrsnl { get; set; }
    }
}
