//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerPrsnlHstryEdu
    {
        public int PerPrsnlHstryEdu_Si { get; set; }
        public string PerPrsnlHstryEdu_Brnch { get; set; }
        public string PerPrsnlHstryEdu_Madrak { get; set; }
        public string PerPrsnlHstryEdu_EduPlc { get; set; }
        public string PerPrsnlHstryEdu_Avg { get; set; }
        public Nullable<System.DateTime> PerPrsnlHstryEdu_DateStr { get; set; }
        public Nullable<System.DateTime> PerPrsnlHstryEdu_DateEnd { get; set; }
        public Nullable<int> PerPrsnl_Si { get; set; }
    }
}
