//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersWorkHoliday
    {
        public int PersWorkHolidays_Si { get; set; }
        public Nullable<int> PersWorkHolidays_Number { get; set; }
        public Nullable<int> PerPyrlPeriod_Si { get; set; }
    }
}
