//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerTaxD
    {
        public int PerTaxD_Si { get; set; }
        public int PerTaxH_Si { get; set; }
        public decimal PerTaxD_Salary_Month { get; set; }
        public decimal PerTaxD_Salary_Year { get; set; }
        public double PerTaxD_Persent { get; set; }
        public decimal PerTaxD_Price { get; set; }
        public Nullable<decimal> PerTaxD_Salary_Day { get; set; }
    
        public virtual PerTaxH PerTaxH { get; set; }
    }
}
