//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerTaxGrp
    {
        public int PerTaxGrp_Si { get; set; }
        public string PerTaxGrp_Cu { get; set; }
        public string PerTaxGrp_Tp { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
    }
}
