//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerWorkPlace
    {
        public int PerWorkPlace_Si { get; set; }
        public string PerWorkPlace_Tp { get; set; }
        public string PerWorkPlace_Cu { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
    }
}
