//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmDSerVice
    {
        public int PmDService_Id { get; set; }
        public Nullable<int> PmDService_Code { get; set; }
        public string PmDService_Desc { get; set; }
        public Nullable<int> PmDPriority_Ref_Id { get; set; }
        public Nullable<int> PmDAccess_Ref_Id { get; set; }
        public Nullable<int> PmDService_Type { get; set; }
        public Nullable<int> PmDCarCategory_Ref_Id { get; set; }
        public Nullable<int> PmDService_Time { get; set; }
    }
}
