//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pmworkmessure
    {
        public int WorkDurMessureId { get; set; }
        public Nullable<int> WorkDurMessureCode { get; set; }
        public string WorkDurMessureTitle { get; set; }
        public string WorkDurMessureTitle_Latin { get; set; }
    }
}
