//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdcLine
    {
        public int PrdcLine_Si { get; set; }
        public Nullable<int> PrdcLineTitle_Si { get; set; }
        public Nullable<int> CtbCost_Si { get; set; }
        public Nullable<int> PrdcStation_Si { get; set; }
        public Nullable<int> PrdcLine_MachineTime { get; set; }
        public Nullable<int> PrdcLine_HumanTime { get; set; }
        public Nullable<double> PrdcLine_ContractorTime { get; set; }
        public Nullable<double> PrdcLine_ScrapValue { get; set; }
        public Nullable<bool> PrdcLine_ChangeInWorkOrder { get; set; }
    
        public virtual CtbCost CtbCost { get; set; }
        public virtual PrdcLineTitle PrdcLineTitle { get; set; }
        public virtual PrdcStation PrdcStation { get; set; }
    }
}
