//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdcWorkOrderH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdcWorkOrderH()
        {
            this.PrdcWorkOrderDInfoes = new HashSet<PrdcWorkOrderDInfo>();
        }
    
        public int PrdcWorkOrderH_Si { get; set; }
        public string PrdcWorkOrderH_Cu { get; set; }
        public string PrdcWorkOrderH_Date { get; set; }
        public Nullable<int> PrdcWorkOrderType_Si { get; set; }
        public Nullable<short> PrdcWorkOrderH_Priority { get; set; }
        public Nullable<bool> PrdcWorkOrderH_Status { get; set; }
        public string PrdcWorkOrderH_FromDate { get; set; }
        public string PrdcWorkOrderH_ToDate { get; set; }
        public string PrdcWorkOrderH_Description { get; set; }
        public Nullable<bool> PrdcWorkOrderH_Lock { get; set; }
        public Nullable<bool> PrdcWorkOrderH_IsTrace1 { get; set; }
        public Nullable<bool> PrdcWorkOrderH_IsTrace2 { get; set; }
        public string PrdcWorkOrderH_CreatorUser { get; set; }
        public string PrdcWorkOrderH_ConfirmationUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdcWorkOrderDInfo> PrdcWorkOrderDInfoes { get; set; }
    }
}
