//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurBuyH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurBuyH()
        {
            this.PurBuyDs = new HashSet<PurBuyD>();
            this.PurIncDecFactorHs = new HashSet<PurIncDecFactorH>();
        }
    
        public int PurBuyH_Si { get; set; }
        public Nullable<System.DateTime> PurBuyH_Dt { get; set; }
        public string PurBuyH_Cu { get; set; }
        public string PurBuyH_Ds { get; set; }
        public Nullable<byte> PurBuyH_Kind { get; set; }
        public Nullable<int> PurVndr_Si { get; set; }
        public Nullable<int> PurOrderH_Si { get; set; }
        public Nullable<int> PurOrdBuyH_Si { get; set; }
        public string PurBuyH_CustNo { get; set; }
        public Nullable<decimal> PurBuyH_Price { get; set; }
        public string PurBuyH_Desc { get; set; }
        public string PurBuyH_FileName { get; set; }
        public byte[] PurBuyH_File { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurBuyD> PurBuyDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurIncDecFactorH> PurIncDecFactorHs { get; set; }
    }
}
