//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurIncDecFactorH
    {
        public int PurIncDecFactorH_Si { get; set; }
        public int PurIncDecFactorType_Si { get; set; }
        public int PurBuyH_Si { get; set; }
        public decimal PurIncDecFactorH_Amnt { get; set; }
        public Nullable<double> PurIncDecFactorH_perc { get; set; }
        public string PurIncDecFactorH_Desc { get; set; }
    
        public virtual PurBuyH PurBuyH { get; set; }
        public virtual PurIncDecFactorType PurIncDecFactorType { get; set; }
    }
}
