//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurOrderH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurOrderH()
        {
            this.PurOrderDs = new HashSet<PurOrderD>();
            this.PurOrdvndrs = new HashSet<PurOrdvndr>();
            this.PurPreInvcHes = new HashSet<PurPreInvcH>();
        }
    
        public int PurOrderH_Si { get; set; }
        public Nullable<int> PurOrderH_Cu { get; set; }
        public Nullable<System.DateTime> PurOrderH_DT { get; set; }
        public string PurOrderH_Tp { get; set; }
        public Nullable<int> PurOrderH_KindOrd { get; set; }
        public Nullable<int> PurOrderH_process { get; set; }
        public Nullable<int> PurResp_Si { get; set; }
        public Nullable<bool> PurOrderH_OK { get; set; }
        public Nullable<int> PurOrderH_BuyKind { get; set; }
        public Nullable<int> PurReqstH_Si { get; set; }
        public Nullable<int> PurOrderH_Payer { get; set; }
        public Nullable<int> PurOrderH_PayKind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurOrderD> PurOrderDs { get; set; }
        public virtual PurOrdPayer PurOrdPayer { get; set; }
        public virtual PurOrdPayKind PurOrdPayKind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurOrdvndr> PurOrdvndrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurPreInvcH> PurPreInvcHes { get; set; }
    }
}
