//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurOrdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurOrdr()
        {
            this.PurEnqries = new HashSet<PurEnqry>();
            this.PurInvcDs = new HashSet<PurInvcD>();
            this.PurRqstDs = new HashSet<PurRqstD>();
        }
    
        public int PurOrdr_Si { get; set; }
        public Nullable<System.DateTime> PurOrdr_DT { get; set; }
        public int InvGds_Si { get; set; }
        public int PurVndr_Si { get; set; }
        public double PurOrdr_Qty { get; set; }
        public decimal PurOrdr_UntPrc { get; set; }
        public decimal PurOrdr_Total { get; set; }
        public string PurOrdr_Tp { get; set; }
        public int PurEnqry_Si { get; set; }
        public Nullable<int> PurInvcH_Si { get; set; }
        public Nullable<byte> PurOrdHCnfrm_Si { get; set; }
        public string PurOrdHCnfrm_Desc { get; set; }
        public Nullable<int> PurResP_Si { get; set; }
    
        public virtual InvGd InvGd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurEnqry> PurEnqries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurInvcD> PurInvcDs { get; set; }
        public virtual PurInvcH PurInvcH { get; set; }
        //public virtual PurVndr PurVndr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurRqstD> PurRqstDs { get; set; }
    }
}
