//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurOrdBuyH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurOrdBuyH()
        {
            this.PurOrdBuyDs = new HashSet<PurOrdBuyD>();
        }
    
        public int PurOrdBuyH_Si { get; set; }
        public string PurOrdBuyH_Cu { get; set; }
        public Nullable<System.DateTime> PurOrdBuyH_DT { get; set; }
        public string PurOrdBuyH_Ds { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurOrdBuyD> PurOrdBuyDs { get; set; }
    }
}
