//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurPayPaperH
    {
        public int PurPayPaperH_Si { get; set; }
        public string PurPayPaperH_Cu { get; set; }
        public string PurPayPaperH_Ds { get; set; }
        public string PurPayPaperH_Dsc { get; set; }
        public string PurPayPaperH_Stmp { get; set; }
        public Nullable<System.DateTime> PurPayPaperH_StmpCDT { get; set; }
        public string PurPayPaperH_Cu2 { get; set; }
    }
}
