//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurPreInvcD
    {
        public int PurPreInvcD_Si { get; set; }
        public Nullable<int> PurPreInvcH_Si { get; set; }
        public Nullable<int> PurOrderD_Si { get; set; }
        public Nullable<double> PurPreInvcD_Qty { get; set; }
        public Nullable<decimal> PurPreInvcD_Price { get; set; }
        public string PurPreInvcD_Desc { get; set; }
    
        public virtual PurPreInvcH PurPreInvcH { get; set; }
    }
}
