//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurReqstD
    {
        public int PurReqstD_Si { get; set; }
        public int PurReqstH_Si { get; set; }
        public Nullable<double> PurReqstD_Qty { get; set; }
        public string PurReqstD_Tp { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<int> PurReqstD_Usage { get; set; }
        public string PurReqstD_DT { get; set; }
        public Nullable<int> PurOrderH_Si { get; set; }
        public Nullable<int> PurOrderD_Si { get; set; }
        public Nullable<double> PurReqstD_FirstQty { get; set; }
        public Nullable<int> PurchaseOrderDetailID { get; set; }
    
        public virtual PurReqstH PurReqstH { get; set; }
    }
}
