//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurRqstD
    {
        public int PurRqstH_Si { get; set; }
        public int InvGds_Si { get; set; }
        public double PurRqstD_RQty { get; set; }
        public Nullable<int> PurEnqry_Si { get; set; }
        public Nullable<int> PurOrdr_Si { get; set; }
        public string InvDocH_Cu { get; set; }
    
        public virtual InvGd InvGd { get; set; }
        public virtual PurOrdr PurOrdr { get; set; }
        public virtual PurRqstH PurRqstH { get; set; }
    }
}
