//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurVndrGrp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurVndrGrp()
        {
            //this.PurVndrs = new HashSet<PurVndr>();
        }
    
        public int PurVndrGrp_Si { get; set; }
        public string PurVndrGrp_Cu { get; set; }
        public string PurVndrGrp_Tp { get; set; }
        public Nullable<int> PurVndrGrp_SiParent { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<PurVndr> PurVndrs { get; set; }
    }
}
