//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalContractH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalContractH()
        {
            this.SalContractDs = new HashSet<SalContractD>();
        }
    
        public int SalContractH_Si { get; set; }
        public Nullable<int> SalContractH_Cu { get; set; }
        public Nullable<int> SalContractTypeID { get; set; }
        public int SalCust_Si { get; set; }
        public string State { get; set; }
        public string SalContractNumber { get; set; }
        public string SalCntrctH_Ds { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string SalContract_Tp { get; set; }
        public string SalContract_StmpCUs { get; set; }
        public Nullable<System.DateTime> SalContract_StmpCDT { get; set; }
        public string SalContract_StmpMUs { get; set; }
        public Nullable<System.DateTime> SalContract_StmpMDT { get; set; }
        public Nullable<decimal> SalContract_Prc_SumTotal { get; set; }
        public Nullable<decimal> SalContract_Prc_Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalContractD> SalContractDs { get; set; }
        public virtual SalContractTyp SalContractTyp { get; set; }
        public virtual SalCust SalCust { get; set; }
    }
}
