//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalCity
    {
        public int SalCity_Si { get; set; }
        public int SalProvince_Si { get; set; }
        public Nullable<double> SalCity_Cu { get; set; }
        public string SalCity_Tp { get; set; }
        public Nullable<double> Cu2 { get; set; }
    
        public virtual SalProvince SalProvince { get; set; }
    }
}
