//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalCustBnk
    {
        public int SalCustBnk_Si { get; set; }
        public string SalCustBnk_AccountNo { get; set; }
        public string SalCustBnk_branch { get; set; }
        public string SalCustBnk_BankName { get; set; }
        public Nullable<int> SalCust_Si { get; set; }
    }
}
