//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalDclrPrcH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalDclrPrcH()
        {
            this.SalDclrPrcDs = new HashSet<SalDclrPrcD>();
        }
    
        public int SalDclrPrcH_Si { get; set; }
        public Nullable<int> SalDclrPrcH_Cu { get; set; }
        public string SalDclrPrcH_Ds { get; set; }
        public string SalDclrPrcH_Tp { get; set; }
        public Nullable<int> SalBrnch_Si { get; set; }
        public Nullable<bool> SalDclrPrcH_Status { get; set; }
        public string SalDclrPrcH_EndDs { get; set; }
        public string SalDclrPrcH_StmpCUs { get; set; }
        public Nullable<System.DateTime> SalDclrPrcH_StmpCDT { get; set; }
        public string SalDclrPrcH_StmpMUs { get; set; }
        public Nullable<System.DateTime> SalDclrPrcH_StmpMDT { get; set; }
        public string SalDclrPrcH_StmpTime { get; set; }
        public string SalDclrPrcH_StmpTimeEdit { get; set; }
    
        public virtual SalBrnch SalBrnch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalDclrPrcD> SalDclrPrcDs { get; set; }
    }
}
