//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalDlvrr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalDlvrr()
        {
            this.SalInvcHes = new HashSet<SalInvcH>();
            this.SalInvcSrvHs = new HashSet<SalInvcSrvH>();
            this.SalPreInvcHes = new HashSet<SalPreInvcH>();
            this.SalPreInvcSrvHs = new HashSet<SalPreInvcSrvH>();
            this.SalRequestHs = new HashSet<SalRequestH>();
        }
    
        public int SalDlvrr_Si { get; set; }
        public string SalDlvrr_Tp { get; set; }
        public string SalDlvrr_Tel { get; set; }
        public string SalDlvrr_Adrs { get; set; }
        public byte[] SalDlvrr_Photo { get; set; }
        public string SalDlvrr_Tp_En { get; set; }
        public Nullable<double> SalDlvrr_Percent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalInvcH> SalInvcHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalInvcSrvH> SalInvcSrvHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcH> SalPreInvcHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcSrvH> SalPreInvcSrvHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalRequestH> SalRequestHs { get; set; }
    }
}
