//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalDocVchr
    {
        public int SalDocVchr_Si { get; set; }
        public Nullable<int> SalInvcH_Si { get; set; }
        public Nullable<int> SalRetInvcH_Si { get; set; }
        public Nullable<int> AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> AccLC_Si { get; set; }
        public Nullable<int> AccLP_Si { get; set; }
        public string SalDocVchr_Tp { get; set; }
        public decimal SalDocVchr_Debit { get; set; }
        public decimal SalDocVchr_Credit { get; set; }
        public Nullable<decimal> SalDocVchr_DebitC { get; set; }
        public Nullable<decimal> SalDocVchr_CreditC { get; set; }
    
        public virtual SalInvcH SalInvcH { get; set; }
    }
}
