//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalDocLock
    {
        public int SalDocLock_Si { get; set; }
        public System.DateTime SalDocLock_Fr { get; set; }
        public System.DateTime SalDocLock_To { get; set; }
        public string SalDocLock_Tx { get; set; }
        public bool SalDocLock_Active { get; set; }
    }
}
