//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalExportPrmD
    {
        public int SalExportPrmD_Si { get; set; }
        public Nullable<int> SalExportPrmH_Si { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<double> SalExportPrmD_Qty { get; set; }
        public Nullable<double> SalExportPrmD_Qty2 { get; set; }
        public Nullable<int> InvUnt_Si { get; set; }
        public Nullable<decimal> SalExportPrmD_Total { get; set; }
        public Nullable<decimal> SalExportPrmD_UntPrc { get; set; }
        public Nullable<double> SalExportPrmD_Prc_Inc { get; set; }
        public Nullable<double> SalExportPrmD_Prc_Dec { get; set; }
        public Nullable<int> SalOpr_Si { get; set; }
        public string SalOpr_Tp { get; set; }
        public Nullable<double> SalOpr_DefaultValue { get; set; }
        public Nullable<decimal> SalExportPrmD_SumTotal { get; set; }
        public Nullable<int> SalGiftInvGds_Si { get; set; }
        public string SalGiftInvGds_Tp { get; set; }
        public Nullable<double> SalGiftInvGds_Total { get; set; }
        public Nullable<double> SalGiftInvGds_Qty { get; set; }
        public Nullable<bool> SalExportPrmD_GiftOk { get; set; }
        public Nullable<int> SalOpr_Si_2 { get; set; }
        public string SalOpr_TP_2 { get; set; }
        public Nullable<double> SalOpr_DefaultValue_2 { get; set; }
        public Nullable<double> SalExportPrmD_Prc_Dec_2 { get; set; }
        public Nullable<double> SalExportPrmD_Prc_Inc_2 { get; set; }
        public Nullable<double> SalExportPrmD_TotalC { get; set; }
        public Nullable<double> SalExportPrmD_UntPrcC { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<int> SalGiftD_Si { get; set; }
        public string SalExportPrmD_Tp { get; set; }
        public Nullable<decimal> SalExportPrmD_SumPrc_Dec { get; set; }
        public Nullable<decimal> SalExportPrmD_SumPrc_Inc { get; set; }
        public Nullable<int> InvGdsTyp_Si { get; set; }
        public Nullable<int> SalOpr_Si_3 { get; set; }
        public string SalOpr_TP_3 { get; set; }
        public Nullable<double> SalOpr_DefaultValue_3 { get; set; }
        public Nullable<double> SalExportPrmD_Prc_Dec_3 { get; set; }
        public Nullable<double> SalExportPrmD_Prc_Inc_3 { get; set; }
        public string BatchNumberD { get; set; }
        public Nullable<System.DateTime> SalExportPrmD_Expiredate { get; set; }
        public Nullable<int> InvUnt_SiDest { get; set; }
        public Nullable<double> SalExportPrmD_QtyDest { get; set; }
        public Nullable<int> SalExportPrmD_Si_Parent { get; set; }
        public Nullable<int> SalGiftDD_Si { get; set; }
    
        public virtual SalExportPrmH SalExportPrmH { get; set; }
    }
}
