//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePreInvoiceOperation
    {
        public int SalePreInvoiceOperationID { get; set; }
        public int SalePreInvoiceID { get; set; }
        public int SalOpr_Si { get; set; }
        public double OperationTotalPrice { get; set; }
    
        public virtual SalePreInvoice SalePreInvoice { get; set; }
    }
}
