//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalExportPrmHOpr
    {
        public int SalExportPrmHOpr_Si { get; set; }
        public Nullable<int> SalExportPrmH_Si { get; set; }
        public Nullable<int> SalOpr_Si { get; set; }
        public Nullable<decimal> SalExportPrmHOpr_Value { get; set; }
        public Nullable<decimal> SalExportPrmHOpr_CalcValue { get; set; }
    }
}
