//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalExportPrmH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalExportPrmH()
        {
            this.SalExportPrmDs = new HashSet<SalExportPrmD>();
        }
    
        public int SalExportPrmH_Si { get; set; }
        public Nullable<int> SalExportPrmH_Cu { get; set; }
        public string SalExportPrmH_Tp { get; set; }
        public string SalExportPrmH_Ds { get; set; }
        public Nullable<int> SalPreInvcH_Si { get; set; }
        public Nullable<int> InvDocH_AccM_Si { get; set; }
        public Nullable<short> SalExportPrmH_RfrncTyp { get; set; }
        public Nullable<decimal> SalExportPrmH_Prc_SumTotal { get; set; }
        public Nullable<decimal> SalExportPrmH_Prc_Inc { get; set; }
        public Nullable<decimal> SalExportPrmH_Prc_Dec { get; set; }
        public Nullable<decimal> SalExportPrmH_Prc_Total { get; set; }
        public Nullable<int> InvInvt_Si { get; set; }
        public Nullable<int> SalCust_Si { get; set; }
        public string SalExportPrmH_StmpCUs { get; set; }
        public Nullable<System.DateTime> SalExportPrmH_StmpCDT { get; set; }
        public string SalExportPrmH_StmpMUs { get; set; }
        public Nullable<System.DateTime> SalExportPrmH_StmpMDT { get; set; }
        public Nullable<int> SalBrnch_Si { get; set; }
        public Nullable<int> SalTyp_Si { get; set; }
        public Nullable<int> SalExportPrmH_StS { get; set; }
        public string SalExportPrmH_Cu2 { get; set; }
        public Nullable<System.DateTime> SalExportPrmH_Dm { get; set; }
        public Nullable<decimal> SalExportPrmH_Prc_SumTotalC { get; set; }
        public Nullable<int> SalExportPrmH_Si_2 { get; set; }
        public Nullable<int> SalIntrmd_Si { get; set; }
        public Nullable<int> SalDrvr_Si { get; set; }
        public string BatchNumberH { get; set; }
        public Nullable<int> SalExpInvcH_Good { get; set; }
        public string SaExpInvcH_RcvMthd { get; set; }
        public string SalExpInvcH_DlvLoc { get; set; }
        public Nullable<int> SalDlvrr_Si { get; set; }
        public string SalExportPrmH_BarNo { get; set; }
        public string SalExportPrmH_Drivername { get; set; }
        public string DescDriver { get; set; }
        public Nullable<int> SalDriver_Si { get; set; }
        public Nullable<int> SiAccM { get; set; }
        public Nullable<bool> SalExportPrmH_Lock { get; set; }
        public Nullable<int> SalExportPrmH_Prc_SumQty { get; set; }
        public Nullable<int> SalPreprint { get; set; }
        public Nullable<int> CtbAddrs_Si { get; set; }
        public string SalExportPrmH_StmpTime { get; set; }
        public string SalExportPrmH_StmpTimeEdit { get; set; }
        public Nullable<int> SalResp_Si { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalExportPrmD> SalExportPrmDs { get; set; }
        public virtual SalPreInvcH SalPreInvcH { get; set; }
    }
}
