//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalGiftH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalGiftH()
        {
            this.SalGiftDs = new HashSet<SalGiftD>();
        }
    
        public int SalGiftH_Si { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<decimal> InvGds_Qty { get; set; }
        public Nullable<decimal> InvGds_Total { get; set; }
        public Nullable<byte> SalGift_AcsMny { get; set; }
        public Nullable<bool> SalGift_Active { get; set; }
        public string SalGiftH_Ds { get; set; }
        public string SalGiftH_DsEnd { get; set; }
        public Nullable<int> SalBrnch_Si { get; set; }
        public Nullable<int> SalCustGrp_Si { get; set; }
        public string SalGiftH_User { get; set; }
        public string SalGiftH_Cu { get; set; }
        public string SalGiftH_Tp { get; set; }
        public string SalGiftH_UserEdit { get; set; }
        public Nullable<System.DateTime> SalGiftH_StmpCDT { get; set; }
        public string SalGiftH_StmpTime { get; set; }
        public string SalGiftH_StmpTimeEdit { get; set; }
        public Nullable<System.DateTime> SalGiftH_StmpMDT { get; set; }
        public Nullable<bool> SalGiftH_Lock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalGiftD> SalGiftDs { get; set; }
    }
}
