//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalGdsRetAcc
    {
        public int SalGdsRetAcc_Si { get; set; }
        public int InvGds_Si { get; set; }
        public int SalGdsRetAcc_AccM_Si { get; set; }
        public Nullable<int> SalGdsRetAcc_AccT_Si { get; set; }
        public Nullable<int> SalGdsRetAcc_AccC_Si { get; set; }
        public Nullable<int> SalGdsRetAcc_AccP_Si { get; set; }
    
        public virtual CtbAccM CtbAccM { get; set; }
        public virtual CtbAccT CtbAccT { get; set; }
        public virtual InvGd InvGd { get; set; }
    }
}
