//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalGiftD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalGiftD()
        {
            this.SalGiftDDs = new HashSet<SalGiftDD>();
        }
    
        public int SalGiftD_Si { get; set; }
        public int SalGiftH_Si { get; set; }
        public int InvGds_Si { get; set; }
        public Nullable<decimal> InvGds_Qty { get; set; }
        public Nullable<decimal> InvGds_Total { get; set; }
        public Nullable<int> InvUnt_Si { get; set; }
        public Nullable<int> InvGdsTyp_Si { get; set; }
        public Nullable<int> InvUnt_SiDest { get; set; }
        public Nullable<decimal> InvGds_QtyDest { get; set; }
    
        public virtual SalGiftH SalGiftH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalGiftDD> SalGiftDDs { get; set; }
    }
}
