//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalInvcSrvAttach
    {
        public int SalInvcSrvAttach_Si { get; set; }
        public string SalInvcSrvAttach_Ds { get; set; }
        public string SalInvcSrvAttach_Tp { get; set; }
        public string SalInvcSrvAttach_FileName { get; set; }
        public byte[] SalInvcSrvAttach_File { get; set; }
        public Nullable<int> SalInvcSrvH_Si { get; set; }
    }
}
