//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalInvcAttach
    {
        public int SalInvcAttach_Si { get; set; }
        public string SalInvcAttach_Ds { get; set; }
        public string SalInvcAttach_Tp { get; set; }
        public string SalInvcAttach_FileName { get; set; }
        public byte[] SalInvcAttach_File { get; set; }
        public Nullable<int> SalInvch_Si { get; set; }
    
        public virtual SalInvcH SalInvcH { get; set; }
    }
}
