//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalInvcSrvH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalInvcSrvH()
        {
            this.SalInvcSrvDs = new HashSet<SalInvcSrvD>();
            this.SalInvcSrvOprs = new HashSet<SalInvcSrvOpr>();
        }
    
        public int SalInvcSrvH_Si { get; set; }
        public Nullable<int> SalInvcSrvH_Cu { get; set; }
        public Nullable<int> SalInvcSrvH_Cu2 { get; set; }
        public string SalInvcSrvH_Ds { get; set; }
        public string SalInvcSrvH_Tp { get; set; }
        public decimal SalInvcSrvH_Prc_SumTotal { get; set; }
        public decimal SalInvcSrvH_Prc_Inc { get; set; }
        public decimal SalInvcSrvH_Prc_Dec { get; set; }
        public decimal SalInvcSrvH_Prc_Total { get; set; }
        public bool SalInvcSrvH_Cancelled { get; set; }
        public bool SalInvcSrvH_AccDoc { get; set; }
        public bool SalInvcSrvH_PrcRcvd { get; set; }
        public int SalCust_Si { get; set; }
        public Nullable<int> SalBrnch_Si { get; set; }
        public Nullable<int> SalTyp_Si { get; set; }
        public Nullable<int> SalIntrmd_Si { get; set; }
        public Nullable<int> SalResp_Si { get; set; }
        public Nullable<int> SalDrvr_Si { get; set; }
        public Nullable<int> SalDlvrr_Si { get; set; }
        public string SalInvcSrvH_StmpCUs { get; set; }
        public Nullable<System.DateTime> SalInvcSrvH_StmpCDT { get; set; }
        public string SalInvcSrvH_StmpMUs { get; set; }
        public Nullable<System.DateTime> SalInvcSrvH_StmpMDT { get; set; }
        public Nullable<short> SalInvcSrvH_RfrncTyp { get; set; }
        public string SalInvcSrvH_Reference { get; set; }
        public Nullable<bool> SalInvcSrvH_Lock { get; set; }
        public Nullable<decimal> SalInvcSrvH_Prc_SumTotalC { get; set; }
        public Nullable<double> SalInvcSrvH_Prc_SumQty { get; set; }
        public Nullable<int> SalPreInvcSrvH_Si { get; set; }
        public Nullable<System.DateTime> SalInvcSrvH_Dm { get; set; }
        public string BatchNumberH { get; set; }
        public Nullable<int> ERPSystemID { get; set; }
        public Nullable<int> ERPReferenceIdentityID { get; set; }
    
        public virtual SalBrnch SalBrnch { get; set; }
        public virtual SalCust SalCust { get; set; }
        public virtual SalDlvrr SalDlvrr { get; set; }
        public virtual SalDrvr SalDrvr { get; set; }
        public virtual SalIntrmd SalIntrmd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalInvcSrvD> SalInvcSrvDs { get; set; }
        public virtual SalResp SalResp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalInvcSrvOpr> SalInvcSrvOprs { get; set; }
    }
}
