//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPreInvcH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalPreInvcH()
        {
            this.SalExportPrmHs = new HashSet<SalExportPrmH>();
            this.SalPreInvcAttaches = new HashSet<SalPreInvcAttach>();
            this.SalPreInvcDs = new HashSet<SalPreInvcD>();
            this.SalPreInvcOprs = new HashSet<SalPreInvcOpr>();
        }
    
        public int SalPreInvcH_Si { get; set; }
        public Nullable<int> SalPreInvcH_Cu { get; set; }
        public string SalPreInvcH_Ds { get; set; }
        public string SalPreInvcH_Tp { get; set; }
        public short SalPreInvcH_RfrncTyp { get; set; }
        public string SalPreInvcH_Reference { get; set; }
        public string SalPreInvcH_DlvLoc { get; set; }
        public string SalPreInvcH_RcvMthd { get; set; }
        public decimal SalPreInvcH_Prc_SumTotal { get; set; }
        public Nullable<decimal> SalPreInvcH_Prc_SumTotalC { get; set; }
        public decimal SalPreInvcH_Prc_Inc { get; set; }
        public decimal SalPreInvcH_Prc_Dec { get; set; }
        public decimal SalPreInvcH_Prc_Total { get; set; }
        public byte SalPreInvcH_Status { get; set; }
        public Nullable<short> SalPreInvcH_ExprTime { get; set; }
        public string SalPreInvcH_ExprDate { get; set; }
        public int SalCust_Si { get; set; }
        public Nullable<int> SalBrnch_Si { get; set; }
        public Nullable<int> SalTyp_Si { get; set; }
        public Nullable<int> SalIntrmd_Si { get; set; }
        public Nullable<int> SalInvcH_Si { get; set; }
        public Nullable<int> SalResp_Si { get; set; }
        public Nullable<int> SalDrvr_Si { get; set; }
        public Nullable<int> SalDlvrr_Si { get; set; }
        public Nullable<int> InvInvt_Si { get; set; }
        public Nullable<bool> SalPreInvcH_Lock { get; set; }
        public string SalPreInvcH_StmpCUs { get; set; }
        public Nullable<System.DateTime> SalPreInvcH_StmpCDT { get; set; }
        public string SalPreInvcH_StmpMUs { get; set; }
        public Nullable<System.DateTime> SalPreInvcH_StmpMDT { get; set; }
        public Nullable<int> SalGiftInvGds_Si { get; set; }
        public Nullable<double> SalPreInvcH_Gift_Total { get; set; }
        public Nullable<double> SalPreInvcH_Prc_Gift { get; set; }
        public Nullable<System.DateTime> SalPreInvcH_Dm { get; set; }
        public Nullable<decimal> SalPreInvcH_Prc_Inc_2 { get; set; }
        public Nullable<decimal> SalPreInvcH_Prc_Dec_2 { get; set; }
        public Nullable<int> SalPreInvcH_Cu2 { get; set; }
        public Nullable<decimal> SalExportPrmH_Prc_SumtotalC { get; set; }
        public Nullable<double> SalPreInvcH_Prc_SumQty { get; set; }
        public Nullable<int> SalPreprint { get; set; }
        public Nullable<int> Salpreinvch_SndInv { get; set; }
        public Nullable<int> InvDocH_AccM_Si { get; set; }
        public string BatchNumberH { get; set; }
        public Nullable<int> SalPreInvcH_Good { get; set; }
        public string DescDriver { get; set; }
        public string SalPreInvcH_BarNo { get; set; }
        public string SalPreInvcH_DriverName { get; set; }
        public Nullable<int> SalDriver_Si { get; set; }
        public Nullable<int> Salprint { get; set; }
        public Nullable<int> SalePreInvoiceID { get; set; }
        public Nullable<int> SiAccM { get; set; }
        public Nullable<int> Salvariety_Si { get; set; }
        public Nullable<double> Remain { get; set; }
        public Nullable<double> SalPreInvcH_SumGrantCust { get; set; }
        public Nullable<double> SalPreInvcH_SumGrantIntrmd { get; set; }
        public Nullable<int> SalpreInvcH_RunNum { get; set; }
        public Nullable<bool> SalpreInvcH_RunNumAccept { get; set; }
        public Nullable<int> SalpreInvcH_INO { get; set; }
        public byte[] SignImage { get; set; }
        public string SalPreInvcH_StmpTime { get; set; }
        public string SalPreInvcH_StmpTimeEdit { get; set; }
        public Nullable<int> SalRequestH_Si { get; set; }
        public Nullable<int> CtbAddrs_Si { get; set; }
        public Nullable<int> SiCost { get; set; }
        public Nullable<int> SalExportPrmH_Si { get; set; }
        public Nullable<double> SalPreInvcH_Prc_SumQtyDest { get; set; }
        public Nullable<double> SalPreInvcH_SumQtyDestNotGiftOk { get; set; }
        public Nullable<double> SalPreInvcH_SumQtyDestwithGiftOk { get; set; }
        public Nullable<double> SalPreInvcH_SumQtyDest { get; set; }
        public string SalPreInvcH_DsAccept { get; set; }
    
        public virtual SalBrnch SalBrnch { get; set; }
        public virtual SalCust SalCust { get; set; }
        public virtual SalDlvrr SalDlvrr { get; set; }
        public virtual SalDrvr SalDrvr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalExportPrmH> SalExportPrmHs { get; set; }
        public virtual SalIntrmd SalIntrmd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcAttach> SalPreInvcAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcD> SalPreInvcDs { get; set; }
        public virtual SalResp SalResp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcOpr> SalPreInvcOprs { get; set; }
    }
}
