//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPreInvcD
    {
        public int SalPreInvcD_Si { get; set; }
        public int SalPreInvcH_Si { get; set; }
        public int InvGds_Si { get; set; }
        public Nullable<int> SalPreInvcD_Row { get; set; }
        public double SalPreInvcD_Qty { get; set; }
        public Nullable<double> SalPreInvcD_Qty2 { get; set; }
        public decimal SalPreInvcD_UntPrc { get; set; }
        public decimal SalPreInvcD_Total { get; set; }
        public string SalPreInvcD_Tp { get; set; }
        public Nullable<int> InvUnt_Si { get; set; }
        public Nullable<int> InvGdsTyp_Si { get; set; }
        public Nullable<int> SalOpr_Si { get; set; }
        public string SalOpr_Tp { get; set; }
        public Nullable<double> SalOpr_DefaultValue { get; set; }
        public Nullable<decimal> SalOprInc { get; set; }
        public Nullable<decimal> SalOprDEc { get; set; }
        public Nullable<decimal> SalpreInvcD_Prc_Dec { get; set; }
        public Nullable<decimal> SalpreInvcD_Prc_Inc { get; set; }
        public Nullable<decimal> SalPreInvCd_SumTotal { get; set; }
        public Nullable<int> SalGiftInvGds_Si { get; set; }
        public string SalGiftInvGds_Tp { get; set; }
        public Nullable<double> SalGiftInvGds_Total { get; set; }
        public Nullable<double> SalGiftInvGds_Qty { get; set; }
        public Nullable<int> SalGiftD_Si { get; set; }
        public Nullable<bool> SalPreInvcD_GiftOk { get; set; }
        public Nullable<double> SalPreInvcD_TotalC { get; set; }
        public Nullable<double> SalPreInvcD_UntPrcC { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<decimal> SalpreInvcD_Prc_Inc_2 { get; set; }
        public Nullable<decimal> SalPreInvcD_Prc_Dec_2 { get; set; }
        public Nullable<int> SalOpr_Si_2 { get; set; }
        public string SalOpr_Tp_2 { get; set; }
        public Nullable<double> SalOpr_DefaultValue_2 { get; set; }
        public Nullable<double> SalPreInvcD_SumPrc_Dec { get; set; }
        public Nullable<double> SalPreInvcD_SumPrc_Inc { get; set; }
        public Nullable<int> SalOpr_Si_3 { get; set; }
        public string SalOpr_Tp_3 { get; set; }
        public Nullable<double> SalOpr_DefaultValue_3 { get; set; }
        public Nullable<double> SalpreInvcD_Prc_Inc_3 { get; set; }
        public Nullable<double> SalPreInvcD_Prc_Dec_3 { get; set; }
        public string BatchNumberD { get; set; }
        public string InvBatchNumber_Code { get; set; }
        public Nullable<System.DateTime> SalPreInvcD_Expiredate { get; set; }
        public Nullable<double> Remain { get; set; }
        public Nullable<double> SalPreInvcD_GrntCust { get; set; }
        public Nullable<double> SalPreInvcD_coefficientCust { get; set; }
        public Nullable<double> SalPreInvcD_TotalGrantCust { get; set; }
        public Nullable<double> SalPreInvcD_GrntIntrmd { get; set; }
        public Nullable<double> SalPreInvcD_coefficientintrmd { get; set; }
        public Nullable<double> SalPreInvcD_TotalGrantIntrmd { get; set; }
        public Nullable<int> InvUnt_SiDest { get; set; }
        public Nullable<double> SalPreInvcD_QtyDest { get; set; }
        public Nullable<int> SalPreInvcD_Si_Parent { get; set; }
        public Nullable<int> SalGiftDD_Si { get; set; }
    
        public virtual InvGd InvGd { get; set; }
        public virtual InvUnt InvUnt { get; set; }
        public virtual SalOpr SalOpr { get; set; }
        public virtual SalPreInvcH SalPreInvcH { get; set; }
    }
}
