//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPursue
    {
        public int SalPursue_Si { get; set; }
        public Nullable<int> SalCust_Si { get; set; }
        public string SalPursue_DateEnter { get; set; }
        public string SalPursue_DateEdit { get; set; }
        public string SalPursue_DatePursue { get; set; }
        public string SalPursue_Desc { get; set; }
        public string SalPursue_UserSave { get; set; }
        public string SalPursue_UserEdit { get; set; }
        public string SalPursue_Tp { get; set; }
        public byte[] SalPursue_File { get; set; }
        public string SalPursue_FileName { get; set; }
        public bool SalPursue_HaveFile { get; set; }
        public Nullable<bool> SalPursue_IsFinall { get; set; }
        public string SalPursue_pursuitTP { get; set; }
        public Nullable<bool> SalPursue_pursuit { get; set; }
        public string SalPursue_Predict { get; set; }
        public string SalPursue_ChanceSale { get; set; }
        public Nullable<bool> SalPursue_NeedSerach { get; set; }
        public Nullable<bool> SalPursue_NeesSerach { get; set; }
        public Nullable<bool> SalPursue_NeesSearch { get; set; }
    
        public virtual SalCust SalCust { get; set; }
    }
}
