//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPreInvcSrvH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalPreInvcSrvH()
        {
            this.SalPreInvcSrvDs = new HashSet<SalPreInvcSrvD>();
            this.SalPreInvcSrvOprs = new HashSet<SalPreInvcSrvOpr>();
        }
    
        public int SalPreInvcSrvH_Si { get; set; }
        public Nullable<int> SalPreInvcSrvH_Cu { get; set; }
        public string SalPreInvcSrvH_Ds { get; set; }
        public string SalPreInvcSrvH_Tp { get; set; }
        public short SalPreInvcSrvH_RfrncTyp { get; set; }
        public string SalPreInvcSrvH_Reference { get; set; }
        public string SalPreInvcSrvH_DlvLoc { get; set; }
        public string SalPreInvcSrvH_RcvMthd { get; set; }
        public decimal SalPreInvcSrvH_Prc_SumTotal { get; set; }
        public decimal SalPreInvcSrvH_Prc_Inc { get; set; }
        public decimal SalPreInvcSrvH_Prc_Dec { get; set; }
        public decimal SalPreInvcSrvH_Prc_Total { get; set; }
        public byte SalPreInvcSrvH_Status { get; set; }
        public Nullable<short> SalPreInvcSrvH_ExprTime { get; set; }
        public string SalPreInvcSrvH_ExprDate { get; set; }
        public int SalCust_Si { get; set; }
        public Nullable<int> SalBrnch_Si { get; set; }
        public Nullable<int> SalTyp_Si { get; set; }
        public Nullable<int> SalIntrmd_Si { get; set; }
        public Nullable<int> SalInvcSrvH_Si { get; set; }
        public Nullable<int> SalResp_Si { get; set; }
        public Nullable<int> SalDrvr_Si { get; set; }
        public Nullable<int> SalDlvrr_Si { get; set; }
        public Nullable<int> SalPRINT_1 { get; set; }
        public string SalPreInvcSrvH_StmpCUs { get; set; }
        public Nullable<System.DateTime> SalPreInvcSrvH_StmpCDT { get; set; }
        public string SalPreInvcSrvH_StmpMUs { get; set; }
        public Nullable<System.DateTime> SalPreInvcSrvH_StmpMDT { get; set; }
        public Nullable<bool> SalPreInvcSrvH_Lock { get; set; }
        public Nullable<int> SalPreInvcSrvH_Prc_SumQty { get; set; }
        public Nullable<System.DateTime> SalPreInvcSrvH_Dm { get; set; }
        public string BatchNumberH { get; set; }
    
        public virtual SalBrnch SalBrnch { get; set; }
        public virtual SalCust SalCust { get; set; }
        public virtual SalDlvrr SalDlvrr { get; set; }
        public virtual SalDrvr SalDrvr { get; set; }
        public virtual SalIntrmd SalIntrmd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcSrvD> SalPreInvcSrvDs { get; set; }
        public virtual SalResp SalResp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcSrvOpr> SalPreInvcSrvOprs { get; set; }
    }
}
