//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPromotionH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalPromotionH()
        {
            this.SalPromotionDs = new HashSet<SalPromotionD>();
        }
    
        public int SalPromotionH_Si { get; set; }
        public Nullable<int> SalPromotionH_Cu { get; set; }
        public string SalPromotionH_Ds { get; set; }
        public string SalPromotionH_Tp { get; set; }
        public Nullable<int> SalBrnch_Si { get; set; }
        public Nullable<bool> SalPromotionH_Status { get; set; }
    
        public virtual SalBrnch SalBrnch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPromotionD> SalPromotionDs { get; set; }
    }
}
