//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPreInvcAttach
    {
        public int SalPreInvcAttach_Si { get; set; }
        public string SalPreInvcAttach_Ds { get; set; }
        public string SalPreInvcAttach_Tp { get; set; }
        public string SalPreInvcAttach_FileName { get; set; }
        public byte[] SalPreInvcAttach_File { get; set; }
        public Nullable<int> SalPreInvch_Si { get; set; }
    
        public virtual SalPreInvcH SalPreInvcH { get; set; }
    }
}
