//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalRequestOpr
    {
        public int SalRequestOpr_Si { get; set; }
        public int SalRequestH_Si { get; set; }
        public int SalOpr_Si { get; set; }
        public decimal SalRequestOpr_Value { get; set; }
        public decimal SalRequestOpr_CalcValue { get; set; }
    
        public virtual SalOpr SalOpr { get; set; }
        public virtual SalRequestH SalRequestH { get; set; }
    }
}
