//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalRegionToSalIntrmd
    {
        public int SalRegionToSalIntrmd_Si { get; set; }
        public Nullable<int> SalIntrmd_Si { get; set; }
        public Nullable<int> SalRegionPath_Si { get; set; }
        public Nullable<int> SalRegion_Si { get; set; }
        public Nullable<System.DateTime> SalRegionToSalIntrmd_FrmDs { get; set; }
        public Nullable<System.DateTime> SalRegionToSalIntrmd_ToDs { get; set; }
        public Nullable<bool> SalRegionToSalIntrmd_Act { get; set; }
    }
}
