//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalRetInvcH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalRetInvcH()
        {
            this.SalRetInvcDs = new HashSet<SalRetInvcD>();
            this.SalRetInvcDSrls = new HashSet<SalRetInvcDSrl>();
            this.SalRetInvcOprs = new HashSet<SalRetInvcOpr>();
        }
    
        public int SalRetInvcH_Si { get; set; }
        public Nullable<int> SalRetInvcH_Cu { get; set; }
        public string SalRetInvcH_Ds { get; set; }
        public string SalRetInvcH_Tp { get; set; }
        public short SalRetInvcH_RfrncTyp { get; set; }
        public string SalRetInvcH_Reference { get; set; }
        public decimal SalRetInvcH_Prc_SumTotal { get; set; }
        public Nullable<decimal> SalRetInvcH_Prc_SumTotalC { get; set; }
        public decimal SalRetInvcH_Prc_Inc { get; set; }
        public decimal SalRetInvcH_Prc_Dec { get; set; }
        public decimal SalRetInvcH_Prc_Total { get; set; }
        public bool SalRetInvcH_AccDoc { get; set; }
        public int SalCust_Si { get; set; }
        public Nullable<int> SalBrnch_Si { get; set; }
        public Nullable<int> SalIntrmd_Si { get; set; }
        public Nullable<int> InvInvt_Si { get; set; }
        public Nullable<int> InvDocH_AccM_Si { get; set; }
        public Nullable<bool> SalRetInvcH_Lock { get; set; }
        public Nullable<bool> SalInvcH_AccDoc { get; set; }
        public Nullable<int> SalTyp_Si { get; set; }
        public Nullable<int> SalInvcH_Si { get; set; }
        public Nullable<int> SalPrint { get; set; }
        public string SalRetInvcH_StmpCUs { get; set; }
        public Nullable<System.DateTime> SalRetInvcH_StmpCDT { get; set; }
        public string SalRetInvcH_StmpMUs { get; set; }
        public Nullable<System.DateTime> SalRetInvcH_StmpMDT { get; set; }
        public Nullable<double> SalRetInvcH_Prc_Gift { get; set; }
        public Nullable<System.DateTime> SalRetInvcH_Dm { get; set; }
        public Nullable<decimal> SalRetInvcH_Prc_Inc_2 { get; set; }
        public Nullable<decimal> SalRetInvcH_Prc_Dec_2 { get; set; }
        public Nullable<double> SalRetInvcH_Prc_SumQty { get; set; }
        public string BatchNumberH { get; set; }
        public Nullable<double> SalRetInvcH_IntrmdPrc { get; set; }
        public Nullable<int> Salvariety_Si { get; set; }
        public Nullable<double> Remain { get; set; }
        public Nullable<int> SalRetInvcH_Cu2 { get; set; }
        public Nullable<int> SiAccM { get; set; }
        public Nullable<int> SalResp_Si { get; set; }
        public Nullable<int> SiCost { get; set; }
        public Nullable<bool> SalRetInvcH_Cancelled { get; set; }
        public Nullable<int> InvDocH_Si { get; set; }
        public string DescDriver { get; set; }
        public string SalRetinvcH_CarNo { get; set; }
        public string SalRetinvcH_BarNo { get; set; }
        public Nullable<int> SalDlvrr_Si { get; set; }
        public Nullable<double> SalRetInvcH_Prc_SumQtyDest { get; set; }
        public Nullable<double> SalRetInvcH_SumQtyDestNotGiftOk { get; set; }
        public Nullable<double> SalRetInvcH_SumQtyDestwithGiftOk { get; set; }
        public Nullable<int> SiProject { get; set; }
    
        //public virtual InvInvt InvInvt { get; set; }
        public virtual SalBrnch SalBrnch { get; set; }
        public virtual SalCust SalCust { get; set; }
        public virtual SalIntrmd SalIntrmd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalRetInvcD> SalRetInvcDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalRetInvcDSrl> SalRetInvcDSrls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalRetInvcOpr> SalRetInvcOprs { get; set; }
    }
}
