//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalSeller
    {
        public int SalSeller_Si { get; set; }
        public string SalSeller_Tp { get; set; }
        public string SalSeller_EconomicalNo { get; set; }
        public string SalSeller_Adress { get; set; }
        public string SalSeller_Tel { get; set; }
    }
}
