//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalSrv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalSrv()
        {
            this.SalInvcSrvDs = new HashSet<SalInvcSrvD>();
            this.SalPreInvcSrvDs = new HashSet<SalPreInvcSrvD>();
            this.SalSrvAccs = new HashSet<SalSrvAcc>();
        }
    
        public int SalSrv_Si { get; set; }
        public string SalSrv_Cu { get; set; }
        public string SalSrv_Tp { get; set; }
        public Nullable<int> SalSrv_SiParent { get; set; }
        public string SalSrv_Unt { get; set; }
        public Nullable<int> SalSrvGrp_Si { get; set; }
        public Nullable<decimal> SalSrv_StdPrc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalInvcSrvD> SalInvcSrvDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPreInvcSrvD> SalPreInvcSrvDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalSrvAcc> SalSrvAccs { get; set; }
    }
}
