//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalUserLevel
    {
        public int SalUserLevel_Si { get; set; }
        public string SalUserLevel_UserCode { get; set; }
        public string SalUserLevel_UserName { get; set; }
        public Nullable<int> SalUserLevel_SiParent { get; set; }
        public Nullable<short> LevelNo { get; set; }
    }
}
