//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StimulReportFile
    {
        public System.Guid StimulReportFileID { get; set; }
        public bool IsStandardReport { get; set; }
        public string FormName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] FileContent { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsPublished { get; set; }
    }
}
