//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsARqstToAsgn
    {
        public int TrsARqstToAsgn_Si { get; set; }
        public Nullable<int> TrsARqst_Si { get; set; }
        public Nullable<int> TrsAsgn_Si { get; set; }
        public Nullable<double> TrsARqstToAsgn_Prc { get; set; }
        public Nullable<int> SiAccT { get; set; }
        public Nullable<int> SiCost { get; set; }
        public Nullable<int> SiProject { get; set; }
        public string TrsARqstToAsgn_Tp { get; set; }
    
        public virtual TrsARqst TrsARqst { get; set; }
    }
}
