//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsAsgn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrsAsgn()
        {
            this.TrsDcAs = new HashSet<TrsDcA>();
        }
    
        public int TrsAsgn_Si { get; set; }
        public string TrsAsgn_Tp { get; set; }
        public string TrsAsgnGrp_Si { get; set; }
        public bool TrsAsgn_Act { get; set; }
        public int AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> AccLC_Si { get; set; }
        public Nullable<int> AccLP_Si { get; set; }
        public Nullable<bool> TrsAsgn_UP { get; set; }
        public Nullable<bool> TrsAsgn_UR { get; set; }
        public byte AccLT_Cnstr { get; set; }
        public byte AccLC_Cnstr { get; set; }
        public byte AccLP_Cnstr { get; set; }
    
        public virtual CtbAccM CtbAccM { get; set; }
        public virtual CtbAccT CtbAccT { get; set; }
        public virtual CtbCost CtbCost { get; set; }
        public virtual CtbProject CtbProject { get; set; }
        public virtual TrsAsgnGrp TrsAsgnGrp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsDcA> TrsDcAs { get; set; }
    }
}
