//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsBnkCnflt
    {
        public int TrsBnkCnflt_Si { get; set; }
        public int TrsRsrc_Si { get; set; }
        public Nullable<System.DateTime> TrsBnkCnflt_Date { get; set; }
        public string TrsBnkCnflt_Desc { get; set; }
        public Nullable<int> TrsBnkCnflt_No { get; set; }
        public Nullable<decimal> TrsBnkCnflt_Debit { get; set; }
        public Nullable<decimal> TrsBnkCnflt_Credit { get; set; }
        public Nullable<decimal> TrsBnkCnflt_Rmndr { get; set; }
        public Nullable<int> TrsDcC_Si { get; set; }
        public string TrsBnkCnflt_Tp { get; set; }
        public string TrsBnkCnflt_AccNo { get; set; }
        public Nullable<int> TrsDcC_Si_Img { get; set; }
    
        public virtual TrsDcC TrsDcC { get; set; }
        public virtual TrsRsrc TrsRsrc { get; set; }
    }
}
