//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsChqP
    {
        public int TrsChqP_Si { get; set; }
        public int AccLT_Si { get; set; }
        public int TrsChqP_BgnNo { get; set; }
        public int TrsChqP_EndNo { get; set; }
        public Nullable<System.DateTime> TrsChqP_DT { get; set; }
        public Nullable<bool> EndCheck { get; set; }
    
        public virtual CtbAccT CtbAccT { get; set; }
    }
}
