//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsChqPUse
    {
        public int TrsChqPUse_Si { get; set; }
        public int TrsChqP_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public int TrsDcC_INo { get; set; }
        public int TrsDcC_Si { get; set; }
        public Nullable<int> TrsDcTyp_Si { get; set; }
        public Nullable<int> TrsCTyp_Si { get; set; }
    }
}
