//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsDcAPreInvc
    {
        public int TrsDcAPreInvc_Si { get; set; }
        public int TrsDcA_Si { get; set; }
        public int SalPreInvcH_Si { get; set; }
    }
}
