//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsDcAttach
    {
        public int TrsDcAttach_Si { get; set; }
        public string TrsDcAttach_Ds { get; set; }
        public string TrsDcAttach_Tp { get; set; }
        public string TrsDcAttach_FileName { get; set; }
        public byte[] TrsDcAttach_File { get; set; }
        public Nullable<int> TrsDc_Si { get; set; }
    
        public virtual TrsDc TrsDc { get; set; }
    }
}
