//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsDcC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrsDcC()
        {
            this.TrsBnkCnflts = new HashSet<TrsBnkCnflt>();
            this.TrsDcAs = new HashSet<TrsDcA>();
            this.TrsDcCAttaches = new HashSet<TrsDcCAttach>();
            this.TrsDcS = new HashSet<TrsDc1>();
            this.TrsDocVchrs = new HashSet<TrsDocVchr>();
        }
    
        public int TrsDcC_Si { get; set; }
        public int TrsDc_Si { get; set; }
        public Nullable<System.DateTime> TrsDcC_DT { get; set; }
        public short TrsCTyp_Si { get; set; }
        public short TrsSts_Si { get; set; }
        public int TrsRsrc_Si { get; set; }
        public decimal TrsDcC_Debit { get; set; }
        public decimal TrsDcC_Credit { get; set; }
        public Nullable<int> TrsChqP_Si { get; set; }
        public Nullable<double> TrsDcC_INo { get; set; }
        public string TrsDcC_IBnk { get; set; }
        public string TrsDcC_IBrnch { get; set; }
        public string TrsDcC_IAccNo { get; set; }
        public string TrsDcC_Tp { get; set; }
        public Nullable<byte> CtbMnth_Si { get; set; }
        public string TrsDcC_AccDesc { get; set; }
        public Nullable<int> AccDocH_Si { get; set; }
        public Nullable<int> TrsAOrdr_Si { get; set; }
        public double TrsDcC_DebitC { get; set; }
        public double TrsDcC_CreditC { get; set; }
        public string TrsDcC_Rfrnc { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<int> SiDocType { get; set; }
        public string TrsDcC_ForMoney { get; set; }
        public string id { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> AccLM_Si { get; set; }
        public Nullable<int> AccLC_Si { get; set; }
        public Nullable<int> AccLP_Si { get; set; }
        public Nullable<System.DateTime> TrsDcC_DT2 { get; set; }
        public string TrsDcC_INOH { get; set; }
        public string TrsDcC_INON { get; set; }
        public string TrsDcC_BrnchNo { get; set; }
        public string TrsDcC_CuDoc { get; set; }
        public string TrsDcc_Intrmd { get; set; }
        public Nullable<bool> TrsDcc_FirstCu { get; set; }
        public Nullable<int> SecCuDoc { get; set; }
        public Nullable<double> DebitC { get; set; }
        public Nullable<double> CreditC { get; set; }
    
        public virtual TrsAOrdr TrsAOrdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsBnkCnflt> TrsBnkCnflts { get; set; }
        public virtual TrsCTyp TrsCTyp { get; set; }
        public virtual TrsDc TrsDc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsDcA> TrsDcAs { get; set; }
        public virtual TrsRsrc TrsRsrc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsDcCAttach> TrsDcCAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsDc1> TrsDcS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrsDocVchr> TrsDocVchrs { get; set; }
    }
}
