//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsDocVchr
    {
        public int TrsDocVchr_Si { get; set; }
        public Nullable<int> TrsDcc_Si { get; set; }
        public Nullable<int> TrsDc_Si { get; set; }
        public int AccLM_Si { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> AccLC_Si { get; set; }
        public Nullable<int> AccLP_Si { get; set; }
        public string TrsDocVchr_Tp { get; set; }
        public decimal TrsDocVchr_Debit { get; set; }
        public decimal TrsDocVchr_Credit { get; set; }
        public Nullable<decimal> TrsDocVchr_DebitC { get; set; }
        public Nullable<decimal> TrsDocVchr_CreditC { get; set; }
        public Nullable<int> AccDocH_Si { get; set; }
    
        public virtual TrsDc TrsDc { get; set; }
        public virtual TrsDcC TrsDcC { get; set; }
    }
}
