//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsGrpUserToUser
    {
        public int TrsGrpUserToUser_Si { get; set; }
        public string UserRec { get; set; }
        public Nullable<int> TrsGrpUser_Si { get; set; }
    }
}
