//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrsSrvDcAInvc
    {
        public int TrsSrvDcAInvc_Si { get; set; }
        public int TrsDcA_Si { get; set; }
        public int SalInvcSrvH_Si { get; set; }
        public Nullable<int> SalCust_Si { get; set; }
        public string SalCust_Tp { get; set; }
        public Nullable<int> SalInvcSrvH_Cu { get; set; }
        public string SalInvcSrvH_Ds { get; set; }
        public Nullable<decimal> SalInvcSrvH_Prc_Total { get; set; }
        public Nullable<decimal> Trs_Price { get; set; }
        public Nullable<decimal> RemainPrc { get; set; }
        public string SalTyp_Tp { get; set; }
        public Nullable<double> Sal_Prc { get; set; }
    }
}
