//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.AddressElectronics = new HashSet<AddressElectronic>();
        }
    
        public int id { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> customerID { get; set; }
        public string detailAddress { get; set; }
        public string ZIPCode { get; set; }
        public Nullable<int> WebsiteAddressRef { get; set; }
    
        public virtual City City { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressElectronic> AddressElectronics { get; set; }
    }
}
