//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivesWarehouse
    {
        public int id { get; set; }
        public string invinvt_cu { get; set; }
        public string rackName { get; set; }
        public Nullable<System.DateTime> regDatetime { get; set; }
        public string regDatetime_Ds { get; set; }
        public string invgds_cu { get; set; }
        public string userName { get; set; }
        public Nullable<decimal> count1 { get; set; }
        public Nullable<decimal> count2 { get; set; }
        public Nullable<System.DateTime> startDate_Dm { get; set; }
        public string startDate_Ds { get; set; }
        public Nullable<System.DateTime> EndDate_Dm { get; set; }
        public string EndDate_Ds { get; set; }
        public string regUserName { get; set; }
    }
}
