//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocWarehouseCharging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocWarehouseCharging()
        {
            this.WarehouseChargingInvgds = new HashSet<WarehouseChargingInvgd>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_Dm { get; set; }
        public string create_Ds { get; set; }
        public Nullable<System.DateTime> confirm_Dm { get; set; }
        public string confirm_Ds { get; set; }
        public string descriptionCreator { get; set; }
        public Nullable<int> doc_Cu { get; set; }
        public string userCreator { get; set; }
        public string userConfirm { get; set; }
        public string descriptionConfirm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseChargingInvgd> WarehouseChargingInvgds { get; set; }
    }
}
