//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialReportHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialReportHeader()
        {
            this.FinancialReportDetails = new HashSet<FinancialReportDetail>();
        }
    
        public int Id { get; set; }
        public string Date { get; set; }
        public string Username { get; set; }
        public decimal TotalSale { get; set; }
        public System.DateTime CreateDm { get; set; }
        public string CreateDs { get; set; }
        public Nullable<System.DateTime> LastUpdateDm { get; set; }
        public string LastUpdateDs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialReportDetail> FinancialReportDetails { get; set; }
    }
}
