//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Initial_ProvisionalDocContradiction
    {
        public int Id { get; set; }
        public Nullable<int> InitialDocId { get; set; }
        public Nullable<decimal> InitialPrice { get; set; }
        public Nullable<decimal> ProvisionalPrice { get; set; }
        public string PersianDate { get; set; }
        public Nullable<System.DateTime> GeorgianDate { get; set; }
        public string Username { get; set; }
    }
}
