//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReceipt_ProvisionalDocContraditionHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryReceipt_ProvisionalDocContraditionHeader()
        {
            this.InventoryReceipt_ProvisionalDocContraditionDetail = new HashSet<InventoryReceipt_ProvisionalDocContraditionDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProvisionalDocId { get; set; }
        public Nullable<System.DateTime> GeorgianDate { get; set; }
        public string PersianDate { get; set; }
        public string Username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryReceipt_ProvisionalDocContraditionDetail> InventoryReceipt_ProvisionalDocContraditionDetail { get; set; }
    }
}
