//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvgdsProperty
    {
        public int InvgdsPropertyId { get; set; }
        public int InvGds_Si { get; set; }
        public Nullable<bool> InvgdsPropertyGuarantee { get; set; }
        public Nullable<double> InvgdsPropertyOrderBrand { get; set; }
    }
}
