//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinHeaderHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JoinHeaderHistory()
        {
            this.JoinDetailHistories = new HashSet<JoinDetailHistory>();
        }
    
        public int Id { get; set; }
        public string No { get; set; }
        public string Desc { get; set; }
        public Nullable<System.DateTime> StartDm { get; set; }
        public string StartDs { get; set; }
        public Nullable<System.DateTime> EndDm { get; set; }
        public string EndDs { get; set; }
        public string User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoinDetailHistory> JoinDetailHistories { get; set; }
    }
}
