//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanic
    {
        public int id { get; set; }
        public Nullable<int> Salinvch_si { get; set; }
        public Nullable<int> salpreinvch_si { get; set; }
        public System.Guid UniqCode { get; set; }
    }
}
