//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderManual_TypeInvgdss
    {
        public int Om_TiId { get; set; }
        public int TypeInvgdssId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<double> ordrManual { get; set; }
    
        public virtual Category1 Category1 { get; set; }
    }
}
