//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceDeclarationHistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> HistoryGeorgianDate { get; set; }
        public string HistoryPersianDate { get; set; }
        public Nullable<int> CtbCustVndrTyp_Si { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> ExpirationDate_Dm { get; set; }
        public string ExpirationDate_Ds { get; set; }
        public Nullable<int> Limitations_Some { get; set; }
        public Nullable<System.DateTime> Update_Dm { get; set; }
        public string Update_Ds { get; set; }
        public Nullable<int> Limitations_Day { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> Percent { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<bool> IsManualPrice { get; set; }
    }
}
