//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalinvcD_Qties2
    {
        public Nullable<decimal> SalInvcD_Qty { get; set; }
        public string SalCust_Cu { get; set; }
        public string SalCust_Tp { get; set; }
        public int SalCust_Si { get; set; }
        public int InvGds_Si { get; set; }
    }
}
