//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scheduling()
        {
            this.SchedulingReports = new HashSet<SchedulingReport>();
        }
    
        public int id { get; set; }
        public string userID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> date_Dm { get; set; }
        public string date_Ds { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> countCall { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchedulingReport> SchedulingReports { get; set; }
    }
}
