//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_getSupplyDetailInfoHatef
    {
        public Nullable<int> InvGds_Si { get; set; }
        public Nullable<decimal> InvDocD_Price { get; set; }
        public Nullable<System.DateTime> InvDocH_Dm { get; set; }
        public string InvDocH_Ds { get; set; }
        public Nullable<int> PricePeriod { get; set; }
        public Nullable<int> PriceDelay { get; set; }
        public double InvGds_QtyMin { get; set; }
        public Nullable<int> OrderPeriod { get; set; }
        public Nullable<int> OrderDelay { get; set; }
    }
}
