//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetMessage
    {
        public string phones { get; set; }
        public Nullable<System.DateTime> date_dm { get; set; }
        public Nullable<bool> isSended { get; set; }
        public string error_message { get; set; }
        public string stringMessage { get; set; }
        public int id { get; set; }
    }
}
