//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPhone
    {
        public int id { get; set; }
        public string number { get; set; }
        public Nullable<int> typePhoneID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> peopleID { get; set; }
        public Nullable<bool> isTelegram { get; set; }
        public int IsDeleted { get; set; }
    }
}
