//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr
    {
        public int TrsDc_Si { get; set; }
        public Nullable<int> TrsDc_Cu { get; set; }
        public System.DateTime TrsDc_DT { get; set; }
        public Nullable<int> TrsDcGrp_Si { get; set; }
        public string TrsDc_Tp { get; set; }
        public bool TrsDc_Share { get; set; }
        public string StmpCUs { get; set; }
        public Nullable<System.DateTime> StmpCDT { get; set; }
        public Nullable<int> trsdc_cu2 { get; set; }
        public Nullable<System.DateTime> TrsDc_StmpCDT { get; set; }
        public string TrsDc_StmpTime { get; set; }
        public string TrsDc_StmpTimeEdit { get; set; }
        public Nullable<System.DateTime> TrsDc_StmpMDT { get; set; }
        public string StmpMUs { get; set; }
        public short TrsDcTyp_Si { get; set; }
        public string TrsDcTyp_Tp { get; set; }
        public string TrsDcTyp_Tp2 { get; set; }
        public int TrsDcC_Si { get; set; }
        public Nullable<System.DateTime> TrsDcC_DT { get; set; }
        public int TrsRsrc_Si { get; set; }
        public decimal TrsDcC_Debit { get; set; }
        public decimal TrsDcC_Credit { get; set; }
        public Nullable<int> TrsChqP_Si { get; set; }
        public Nullable<double> TrsDcC_INo { get; set; }
        public string TrsDcC_IBnk { get; set; }
        public string TrsDcC_IBrnch { get; set; }
        public string TrsDcC_IAccNo { get; set; }
        public string TrsDcC_Tp { get; set; }
        public Nullable<byte> CtbMnth_Si { get; set; }
        public string TrsDcC_AccDesc { get; set; }
        public Nullable<int> TrsAOrdr_Si { get; set; }
        public double TrsDcC_DebitC { get; set; }
        public double TrsDcC_CreditC { get; set; }
        public string TrsDcC_Rfrnc { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<int> SiDocType { get; set; }
        public string TrsDcC_ForMoney { get; set; }
        public Nullable<int> AccLT_Si { get; set; }
        public Nullable<int> TrsDcCAccLM_Si { get; set; }
        public Nullable<System.DateTime> TrsDcC_DT2 { get; set; }
        public string TrsDcC_INOH { get; set; }
        public string TrsDcC_INON { get; set; }
        public string TrsDcC_BrnchNo { get; set; }
        public string TrsDcC_CuDoc { get; set; }
        public string TrsDcc_Intrmd { get; set; }
        public Nullable<bool> TrsDcc_FirstCu { get; set; }
        public int TrsDcA_Si { get; set; }
        public Nullable<int> TrsAsgn_Si { get; set; }
        public int TrsDcAAccLM_Si { get; set; }
        public Nullable<int> TrsDcAAccLT_Si { get; set; }
        public string TrsDcA_Tp { get; set; }
        public decimal TrsDcA_Debit { get; set; }
        public decimal TrsDcA_Credit { get; set; }
        public Nullable<int> TrsDcS_Si { get; set; }
        public string TrsDcA_AccDesc { get; set; }
        public string TrsDcA_Rfrnc { get; set; }
        public string TrsDcA_CuDoc { get; set; }
        public string TrsDcA_Intrmd { get; set; }
        public Nullable<int> SalIntrmd_Si { get; set; }
        public Nullable<bool> TrsDcA_FirstCu { get; set; }
        public Nullable<int> SecCuDoc { get; set; }
        public Nullable<double> DebitC { get; set; }
        public Nullable<double> CreditC { get; set; }
        public Nullable<int> SalResp_Si { get; set; }
        public string SalResp_Tp { get; set; }
        public short TrsCTyp_Si { get; set; }
        public string TrsCTyp_Tp { get; set; }
        public string TrsCTyp_Tp2 { get; set; }
        public short TrsDcATrsSts_si { get; set; }
        public string TrsDcATrsSts_Tp { get; set; }
        public short TrsDccTrsSts_si { get; set; }
        public string TrsDccTrsSts_Tp { get; set; }
    }
}
