//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionScore
    {
        public int id { get; set; }
        public string dateInvoice_Ds { get; set; }
        public string dateInvoice_no { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<System.DateTime> dateInvoice_Dm { get; set; }
        public Nullable<int> invgds_Si { get; set; }
        public Nullable<int> qt { get; set; }
        public Nullable<int> reportSendTelegramID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ReportSendTelegram ReportSendTelegram { get; set; }
    }
}
