//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactinSMSInvoice
    {
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> InvoiceData_Dm { get; set; }
        public string InvoiceData_Ds { get; set; }
        public string price { get; set; }
        public string mobile { get; set; }
        public string fullname { get; set; }
        public string ReturnValue { get; set; }
        public Nullable<System.DateTime> SendDateSMS_Dm { get; set; }
        public string SendDateSMS_Ds { get; set; }
    }
}
