//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeInvgdssToInvgd
    {
        public int TypeInvgdss_Id { get; set; }
        public int Invgds_Si { get; set; }
    
        public virtual TypeInvgdss TypeInvgdss { get; set; }
    }
}
