//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeInvgd
    {
        public int id { get; set; }
        public string invgds_cu { get; set; }
        public string carType { get; set; }
        public string company { get; set; }
        public string carTip { get; set; }
        public string brand { get; set; }
        public Nullable<int> remind { get; set; }
        public Nullable<decimal> maxDifferentPrice { get; set; }
        public Nullable<decimal> minDifferentPrice { get; set; }
        public string subCategory { get; set; }
        public string Category { get; set; }
        public string contrary { get; set; }
        public string name { get; set; }
        public Nullable<bool> Guarantee { get; set; }
        public Nullable<bool> importance { get; set; }
        public Nullable<bool> consumedproduct { get; set; }
        public Nullable<int> typeCategory { get; set; }
        public Nullable<double> orderBrand { get; set; }
        public Nullable<double> orderName { get; set; }
        public Nullable<double> orderCategory { get; set; }
        public Nullable<double> orderSubCategory { get; set; }
    }
}
