//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class websiteSendedInvoice
    {
        public int id { get; set; }
        public Nullable<int> salpreinvch_cu { get; set; }
        public Nullable<int> salinvch_cu { get; set; }
        public Nullable<bool> sendedToWebSite { get; set; }
    }
}
