//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentInterduce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentInterduce()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> organizationID { get; set; }
        public Nullable<int> addressElectronicID { get; set; }
    
        public virtual AddressElectronic AddressElectronic { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
