//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertCheck
    {
        public int id { get; set; }
        public string CheckNumber { get; set; }
        public int TrsChqP_Si { get; set; }
        public string Bank { get; set; }
        public string Hesab_Name { get; set; }
        public decimal Price { get; set; }
        public string forMoney { get; set; }
        public string Date_Ds { get; set; }
        public System.DateTime AlertDate { get; set; }
        public string Message { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> BeforeDay { get; set; }
    }
}
