//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckBook
    {
        public int ID { get; set; }
        public int TrsChqP_Si { get; set; }
        public int AccLT_Si { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
