//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditExtending
    {
        public int ExtendedType_ID { get; set; }
        public System.DateTime CreateDate_Dm { get; set; }
        public string CreateDate_Ds { get; set; }
        public string Customer_Code { get; set; }
        public int id { get; set; }
        public decimal Value { get; set; }
        public Nullable<bool> canSellOriginal { get; set; }
    }
}
