//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCredit
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Day { get; set; }
        public string PreInvoiceNo { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<bool> Active { get; set; }
        public string PersianDate { get; set; }
        public Nullable<System.DateTime> GeorgianDate { get; set; }
    }
}
