//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCreditGood
    {
        public int Id { get; set; }
        public Nullable<int> CustomerCreditId { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> UsedQty { get; set; }
    }
}
