//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecidedPicture
    {
        public int Id { get; set; }
        public string InvGds_Cu { get; set; }
        public Nullable<bool> Accept { get; set; }
        public string UserName { get; set; }
        public string PersianDate { get; set; }
        public Nullable<System.DateTime> GeorgianDate { get; set; }
        public string RejectReason { get; set; }
    }
}
