//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedSerialInvgd
    {
        public int id { get; set; }
        public string invgds_cu { get; set; }
        public string invgds_Serial { get; set; }
        public System.DateTime timeDeleted { get; set; }
        public Nullable<int> requestedDoc_Code { get; set; }
        public Nullable<System.DateTime> timeSet { get; set; }
        public Nullable<int> invdoctyp_si { get; set; }
        public Nullable<int> invdoch_cu { get; set; }
        public string invinvt_cu { get; set; }
        public string userDeleted { get; set; }
        public string userInvinvt_cu { get; set; }
        public Nullable<int> userInvdoctyp_si { get; set; }
        public Nullable<int> userInvdoch_cu { get; set; }
        public Nullable<int> userRequestedDoc_Code { get; set; }
    }
}
