//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialReportDetail
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public int BranchId { get; set; }
        public decimal Sale { get; set; }
        public decimal POS { get; set; }
        public decimal Cash { get; set; }
        public decimal Transfer { get; set; }
        public decimal Credit { get; set; }
        public decimal CurrentInventory { get; set; }
        public decimal TodayInventory { get; set; }
        public decimal YesterdayInventory { get; set; }
        public string LastPayDate { get; set; }
        public bool POSAccepted { get; set; }
        public bool TransferAccepted { get; set; }
        public int FinancialReportHeaderId { get; set; }
    
        public virtual FinancialReportHeader FinancialReportHeader { get; set; }
    }
}
