//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class headerRandromStorage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public headerRandromStorage()
        {
            this.detailRandomStorages = new HashSet<detailRandomStorage>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string startDate_Ds { get; set; }
        public Nullable<System.DateTime> startDate_Dm { get; set; }
        public string invinv_cu { get; set; }
        public Nullable<int> period { get; set; }
        public string userName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailRandomStorage> detailRandomStorages { get; set; }
    }
}
