//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvgdsRequest
    {
        public int Id { get; set; }
        public Nullable<int> RequestNo { get; set; }
        public string SourceInvInvt_Cu { get; set; }
        public string DestinationInvInvt_Cu { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> Invgds_Si { get; set; }
        public string Invgds_Cu { get; set; }
        public string Invgds_Tp { get; set; }
        public Nullable<int> InvUnt_Si { get; set; }
        public string Ds { get; set; }
        public Nullable<System.DateTime> Dm { get; set; }
        public string Requester { get; set; }
        public Nullable<bool> Submitted { get; set; }
    }
}
