//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceScore
    {
        public int id { get; set; }
        public Nullable<int> invoiceNo { get; set; }
        public Nullable<System.DateTime> createDate_dm { get; set; }
        public string createDate_ds { get; set; }
        public string databaseName { get; set; }
        public Nullable<System.DateTime> invoiceDate_dm { get; set; }
        public string invoiceDate_ds { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> salinvch_Si { get; set; }
    }
}
