//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinDetailHistory
    {
        public int Id { get; set; }
        public Nullable<int> InvGds_Si { get; set; }
        public string InvGds_Tp { get; set; }
        public string InvGds_Cu { get; set; }
        public string InvGds_TechNo { get; set; }
        public Nullable<double> Qty { get; set; }
        public string InvInvt_Tp { get; set; }
        public Nullable<int> JoinHeaderHistoryId { get; set; }
    
        public virtual JoinHeaderHistory JoinHeaderHistory { get; set; }
    }
}
