//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class logCall
    {
        public int id { get; set; }
        public string extention { get; set; }
        public string callerID { get; set; }
        public string date_s { get; set; }
        public System.DateTime date_m { get; set; }
        public System.TimeSpan time { get; set; }
        public string name { get; set; }
    }
}
