//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyTransferReceipt
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string TrackingCode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BankName { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PersianDate { get; set; }
        public Nullable<System.DateTime> GeorgianDate { get; set; }
        public Nullable<bool> Confirmation { get; set; }
        public Nullable<bool> Used { get; set; }
    }
}
