//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPointPeriod
    {
        public int InvGds_Si { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<System.DateTime> Dm { get; set; }
        public string Ds { get; set; }
    }
}
