//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultImageTable
    {
        public long TLRequestId { get; set; }
        public string PathImage { get; set; }
        public string ImageName { get; set; }
        public string BrandName { get; set; }
        public string CarTip { get; set; }
        public string CodeFani { get; set; }
        public string CarType { get; set; }
        public string FileName { get; set; }
        public string Company { get; set; }
        public string Invgds_cu { get; set; }
        public int Order { get; set; }
    }
}
