//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalTarget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalTarget()
        {
            this.invgdsTargets = new HashSet<invgdsTarget>();
        }
    
        public int ID { get; set; }
        public int salbrnch_si { get; set; }
        public Nullable<decimal> dailyTarget { get; set; }
        public Nullable<decimal> weeklyTarget { get; set; }
        public Nullable<decimal> monthlyTarget { get; set; }
        public Nullable<int> invgds_si { get; set; }
        public Nullable<int> invgdPeriod { get; set; }
        public Nullable<int> invgdCount { get; set; }
        public Nullable<int> bundleId { get; set; }
        public Nullable<int> bundlePeriod { get; set; }
        public Nullable<int> bundleCount { get; set; }
        public Nullable<System.DateTime> editTime_Dm { get; set; }
        public string editTime_Ds { get; set; }
        public string editUsername { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invgdsTarget> invgdsTargets { get; set; }
    }
}
