//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulingReport
    {
        public int id { get; set; }
        public string text { get; set; }
        public Nullable<int> schedulingID { get; set; }
        public Nullable<System.DateTime> date_Dm { get; set; }
        public string date_Ds { get; set; }
    
        public virtual Scheduling Scheduling { get; set; }
    }
}
