//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetSale
    {
        public int Id { get; set; }
        public System.DateTime start_date { get; set; }
        public string start_persian_date { get; set; }
        public int target_type { get; set; }
        public decimal price { get; set; }
        public int SalBrnch_Si { get; set; }
        public bool is_deleted { get; set; }
    }
}
