//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetSal
    {
        public int id { get; set; }
        public string sal_tp { get; set; }
        public Nullable<int> sal_branch_si { get; set; }
        public Nullable<decimal> sal_target { get; set; }
        public Nullable<decimal> sal_level { get; set; }
        public Nullable<System.DateTime> target_date { get; set; }
    }
}
