//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp2
    {
        public long TLRequestId { get; set; }
        public string Number { get; set; }
        public string Caption { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<System.DateTime> ProcessTimestamp { get; set; }
        public Nullable<bool> Success { get; set; }
        public string ErrorDescription { get; set; }
    }
}
