//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class testInvgds1
    {
        public int InvGds_Si { get; set; }
        public string InvGds_Cu { get; set; }
        public string InvGds_Tp { get; set; }
        public string InvGds_Cm { get; set; }
        public int InvUnt_Si { get; set; }
        public int InvGdsGrp_Si { get; set; }
        public string InvGds_TechNo { get; set; }
        public double InvGds_QtyReal { get; set; }
        public double InvGds_QtyVirtual { get; set; }
        public double InvGds_QtyMin { get; set; }
        public double InvGds_QtyMax { get; set; }
        public double InvGds_QtySafe { get; set; }
        public bool InvGds_PrdGds { get; set; }
        public string InvGds_LName { get; set; }
        public Nullable<int> InvGdsICntry_Si { get; set; }
        public Nullable<int> InvGdsICratr_Si { get; set; }
        public Nullable<decimal> InvGds_PurchasePrc { get; set; }
        public Nullable<int> InvUnt_Si_Sale { get; set; }
        public Nullable<decimal> InvGds_SalePrc { get; set; }
        public Nullable<int> InvUnt_Count { get; set; }
        public Nullable<int> InvGdsStatus_Si { get; set; }
        public Nullable<int> Siaccm { get; set; }
        public string invGdsGrp_SiParent { get; set; }
        public Nullable<int> PurGdsGrp_Si { get; set; }
        public Nullable<decimal> InvGds_PurchasePrcC { get; set; }
        public Nullable<System.DateTime> InvGds_DateBirth { get; set; }
        public Nullable<bool> InvGds_Active { get; set; }
        public Nullable<double> InvGds_QtySale { get; set; }
        public Nullable<bool> InvGds_ActiveSale { get; set; }
        public Nullable<bool> InvGds_ActiveSerial { get; set; }
        public Nullable<double> InvGds_QtyMinOrd { get; set; }
        public Nullable<double> InvGds_QtyBestInWay { get; set; }
        public Nullable<int> InvGds_CountdayInWay { get; set; }
        public Nullable<int> SiAccT { get; set; }
        public Nullable<bool> ShowInWeb { get; set; }
        public Nullable<int> InvbasketGds_Si { get; set; }
        public Nullable<int> InvGdsGrp_Si_2 { get; set; }
        public Nullable<int> CtbCurncy_Si { get; set; }
        public Nullable<int> Plane_No { get; set; }
        public Nullable<int> Employer_No { get; set; }
        public Nullable<double> InvGds_burden { get; set; }
        public Nullable<int> InvGds_height { get; set; }
        public Nullable<int> InvGds_width { get; set; }
        public Nullable<int> InvGds_length { get; set; }
    }
}
