//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeInvgdss_TechNoNew
    {
        public int invgds_TechNo_newId { get; set; }
        public int TypeInvgdssId { get; set; }
        public string invgds_TechNo_new { get; set; }
    
        public virtual TypeInvgdss TypeInvgdss { get; set; }
    }
}
