//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrrrrrrrrrrrrrrrrrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermision
    {
        public string userID { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> monitoring_Access { get; set; }
        public Nullable<bool> phoneBook_Access { get; set; }
        public Nullable<bool> allExtentions_Access { get; set; }
        public Nullable<bool> managePlaneSales_Access { get; set; }
        public Nullable<bool> registerCustomer_Access { get; set; }
        public Nullable<bool> manageUsers_Access { get; set; }
        public Nullable<bool> showPlaneSales_Access { get; set; }
        public Nullable<bool> showSetting_Access { get; set; }
        public Nullable<bool> showLockInvoices_Access { get; set; }
        public Nullable<bool> sendingGroupMessage_Access { get; set; }
        public Nullable<bool> scoreInvgds_Access { get; set; }
        public Nullable<bool> reportsendedMessage_Access { get; set; }
        public Nullable<bool> schedulingMessage_Access { get; set; }
        public Nullable<bool> changeCustomerListNotBuy_Access { get; set; }
        public Nullable<bool> fargoPrinter_Access { get; set; }
        public Nullable<bool> Factor_Access { get; set; }
        public Nullable<bool> DeclarePrice_Access { get; set; }
        public Nullable<bool> AverageUsance_Access { get; set; }
        public Nullable<bool> MonitoringKeyPress { get; set; }
        public Nullable<bool> FreePrice_Access { get; set; }
        public Nullable<bool> SetPriceOriginal_Access { get; set; }
        public Nullable<bool> DesignReport_Access { get; set; }
        public Nullable<bool> Tahvil_Access { get; set; }
        public Nullable<bool> BackTahvil_Access { get; set; }
        public Nullable<bool> PrintBarcode_Access { get; set; }
        public Nullable<bool> DefinitionOnlyEndUser { get; set; }
        public Nullable<bool> EditOnlyEndUser { get; set; }
        public Nullable<bool> Credit_Access { get; set; }
        public Nullable<bool> ConfirmPrintBarcode { get; set; }
        public Nullable<bool> isChangeDollar { get; set; }
        public Nullable<bool> isAdminDemand { get; set; }
        public Nullable<bool> isAdminSale { get; set; }
        public Nullable<bool> AccessCategory { get; set; }
        public Nullable<bool> CreateCategory { get; set; }
        public Nullable<bool> NewBalanceEditCategories { get; set; }
        public Nullable<bool> NewBalanceEditTypeInvgds { get; set; }
        public Nullable<bool> NewBalanceEditPriceList { get; set; }
        public Nullable<bool> SupplyEdit { get; set; }
        public Nullable<bool> DelayedReceipt { get; set; }
        public Nullable<bool> Contradiction { get; set; }
        public Nullable<bool> DelayedContradiction { get; set; }
        public Nullable<bool> TargetDeclration { get; set; }
        public Nullable<bool> PreinvoiceOld { get; set; }
        public Nullable<bool> SaveEditCustomer { get; set; }
        public Nullable<bool> CustomerNotification { get; set; }
        public Nullable<bool> UnConfirmTransfers { get; set; }
        public Nullable<bool> CustomerCredit { get; set; }
        public Nullable<bool> PictureDicide { get; set; }
        public Nullable<bool> ProvisonalDoc { get; set; }
        public Nullable<bool> InitialDoc { get; set; }
        public Nullable<bool> InventoryRec { get; set; }
        public Nullable<bool> UnSalInvForSupply { get; set; }
        public Nullable<bool> UnSalInvForInv { get; set; }
    
        public virtual user user { get; set; }
    }
}
